
import type { Subject, Lesson, SubjectId, StudentReport } from './types';
import { PunjabiIcon, MathIcon, PhysicsIcon, ChemistryIcon, BiologyIcon, ComputerScienceIcon, EnglishIcon } from './components/Icons';

export const SUBJECTS: Subject[] = [
  { id: 'punjabi', name: { en: 'Punjabi', hi: 'पंजाबी', pa: 'ਪੰਜਾਬੀ' }, icon: PunjabiIcon, color: 'bg-orange-500' },
  { id: 'math', name: { en: 'Math', hi: 'गणित', pa: 'ਗਣਿਤ' }, icon: MathIcon, color: 'bg-blue-500' },
  { id: 'physics', name: { en: 'Physics', hi: 'भौतिक विज्ञान', pa: 'ਭੌਤਿਕ ਵਿਗਿਆਨ' }, icon: PhysicsIcon, color: 'bg-indigo-500' },
  { id: 'chemistry', name: { en: 'Chemistry', hi: 'रसायन विज्ञान', pa: 'ਰਸਾਇਣ ਵਿਗਿਆਨ' }, icon: ChemistryIcon, color: 'bg-pink-500' },
  { id: 'biology', name: { en: 'Biology', hi: 'जीवविज्ञान', pa: 'ਜੀਵ ਵਿਗਿਆਨ' }, icon: BiologyIcon, color: 'bg-green-500' },
  { id: 'computer_science', name: { en: 'Computer Sci.', hi: 'कंप्यूटर विज्ञान', pa: 'ਕੰਪਿਊਟਰ ਵਿਗਿਆਨ' }, icon: ComputerScienceIcon, color: 'bg-gray-600' },
  { id: 'english', name: { en: 'English', hi: 'अंग्रेज़ी', pa: 'ਅੰਗਰੇਜ਼ੀ' }, icon: EnglishIcon, color: 'bg-purple-500' },
];

export const LESSONS: Record<SubjectId, Lesson[]> = {
  punjabi: [
    { id: 'pun-11-1', grade: 11, title: { en: 'Punjabi Culture: An Introduction', hi: 'पंजाबी संस्कृति: एक परिचय', pa: 'ਪੰਜਾਬੀ ਸੱਭਿਆਚਾਰ: ਇੱਕ ਜਾਣ-ਪਛਾਣ' }, xp: 50, questions: [
      { question: { en: "Which of these is a famous Punjabi folk dance for women?", hi: "इनमें से कौन सा महिलाओं के लिए एक प्रसिद्ध पंजाबी लोक नृत्य है?", pa: "ਇਹਨਾਂ ਵਿੱਚੋਂ ਕਿਹੜਾ ਔਰਤਾਂ ਲਈ ਇੱਕ ਮਸ਼ਹੂਰ ਪੰਜਾਬੀ ਲੋਕ ਨਾਚ ਹੈ?" }, options: [{en: "Bhangra", hi: "भांगड़ा", pa: "ਭੰਗੜਾ"}, {en: "Giddha", hi: "गिद्दा", pa: "ਗਿੱਧਾ"}, {en: "Kathak", hi: "कथक", pa: "ਕੱਥਕ"}, {en: "Bharatnatyam", hi: "भरतनाट्यम", pa: "ਭਰਤਨਾਟਿਅਮ"}], correctAnswer: 1 },
      { question: { en: "What is the harvest festival of Punjab called?", hi: "पंजाब के फसल उत्सव को क्या कहा जाता है?", pa: "ਪੰਜਾਬ ਦੇ ਵਾਢੀ ਦੇ ਤਿਉਹਾਰ ਨੂੰ ਕੀ ਕਿਹਾ ਜਾਂਦਾ ਹੈ?" }, options: [{en: "Diwali", hi: "दिवाली", pa: "ਦੀਵਾਲੀ"}, {en: "Holi", hi: "होली", pa: "ਹੋਲੀ"}, {en: "Vaisakhi", hi: "वैसाखी", pa: "ਵਿਸਾਖੀ"}, {en: "Lohri", hi: "लोहड़ी", pa: "ਲੋਹੜੀ"}], correctAnswer: 2 },
      { question: { en: "What is a traditional Punjabi dress for men?", hi: "पुरुषों के लिए एक पारंपरिक पंजाबी पोशाक क्या है?", pa: "ਮਰਦਾਂ ਲਈ ਰਵਾਇਤੀ ਪੰਜਾਬੀ ਪਹਿਰਾਵਾ ਕੀ ਹੈ?" }, options: [{en: "Sari", hi: "साड़ी", pa: "ਸਾੜੀ"}, {en: "Kurta-Pyjama", hi: "कुर्ता-पजामा", pa: "ਕੁੜਤਾ-ਪਜਾਮਾ"}, {en: "Dhoti", hi: "धोती", pa: "ਧੋਤੀ"}, {en: "Sherwani", hi: "शेरवानी", pa: "ਸ਼ੇਰਵਾਨੀ"}], correctAnswer: 1 },
      { question: { en: "Which river is NOT associated with the Punjab region?", hi: "कौन सी नदी पंजाब क्षेत्र से संबंधित नहीं है?", pa: "ਕਿਹੜੀ ਨਦੀ ਪੰਜਾਬ ਖੇਤਰ ਨਾਲ ਸਬੰਧਤ ਨਹੀਂ ਹੈ?" }, options: [{en: "Jhelum", hi: "झेलम", pa: "ਜੇਹਲਮ"}, {en: "Chenab", hi: "चिनाब", pa: "ਚਨਾਬ"}, {en: "Ganga", hi: "गंगा", pa: "ਗੰਗਾ"}, {en: "Ravi", hi: "रावी", pa: "ਰਾਵੀ"}], correctAnswer: 2 },
      { question: { en: "What does the word 'Punjab' mean?", hi: "'पंजाब' शब्द का क्या अर्थ है?", pa: "'ਪੰਜਾਬ' ਸ਼ਬਦ ਦਾ ਕੀ ਅਰਥ ਹੈ?" }, options: [{en: "Land of Five Rivers", hi: "पांच नदियों की भूमि", pa: "ਪੰਜ ਦਰਿਆਵਾਂ ਦੀ ਧਰਤੀ"}, {en: "Land of Mountains", hi: "पहाड़ों की भूमि", pa: "ਪਹਾੜਾਂ ਦੀ ਧਰਤੀ"}, {en: "Land of Festivals", hi: "त्योहारों की भूमि", pa: "ਤਿਉਹਾਰਾਂ ਦੀ ਧਰਤੀ"}, {en: "Land of Kings", hi: "राजाओं की भूमि", pa: "ਰਾਜਿਆਂ ਦੀ ਧਰਤੀ"}], correctAnswer: 0 },
    ] },
    { id: 'pun-11-2', grade: 11, title: { en: 'Grammar: Lexicographical Order', hi: 'व्याकरण: कोश-रचना क्रम', pa: 'ਵਿਆਕਰਨ: ਕੋਸ਼-ਤਰਤੀਬ' }, xp: 75, questions: [
      { question: { en: "Which word comes first in Punjabi lexicographical (dictionary) order?", hi: "पंजाबी कोश-रचना (शब्दकोश) क्रम में कौन सा शब्द पहले आता है?", pa: "ਪੰਜਾਬੀ ਕੋਸ਼-ਤਰਤੀਬ (ਡਿਕਸ਼ਨਰੀ) ਅਨੁਸਾਰ ਕਿਹੜਾ ਸ਼ਬਦ ਪਹਿਲਾਂ ਆਉਂਦਾ ਹੈ?" }, options: [{en: "ਉਡਾਣ", hi: "उड़ान", pa: "ਉਡਾਣ"}, {en: "ਅੰਬ", hi: "अंब", pa: "ਅੰਬ"}, {en: "ਸੇਬ", hi: "सेब", pa: "ਸੇਬ"}, {en: "ਹਾਥੀ", hi: "हाथी", pa: "ਹਾਥੀ"}], correctAnswer: 0 },
      { question: { en: "Arrange these words in correct order: 1. ਘਰ, 2. ਕਾਂ, 3. ਗਮਲਾ", hi: "इन शब्दों को सही क्रम में व्यवस्थित करें: 1. घर, 2. कां, 3. गमला", pa: "ਇਹਨਾਂ ਸ਼ਬਦਾਂ ਨੂੰ ਸਹੀ ਕ੍ਰਮ ਵਿੱਚ ਲਗਾਓ: 1. ਘਰ, 2. ਕਾਂ, 3. ਗਮਲਾ" }, options: [{en: "2, 3, 1", hi: "2, 3, 1", pa: "2, 3, 1"}, {en: "3, 1, 2", hi: "3, 1, 2", pa: "3, 1, 2"}, {en: "1, 2, 3", hi: "1, 2, 3", pa: "1, 2, 3"}, {en: "2, 1, 3", hi: "2, 1, 3", pa: "2, 1, 3"}], correctAnswer: 3 },
      { question: { en: "What is the first letter of the Gurmukhi script?", hi: "गुरुमुखी लिपि का पहला अक्षर क्या है?", pa: "ਗੁਰਮੁਖੀ ਲਿਪੀ ਦਾ ਪਹਿਲਾ ਅੱਖਰ ਕਿਹੜਾ ਹੈ?" }, options: [{en: "ਅ", hi: "अ", pa: "ਅ"}, {en: "ਸ", hi: "स", pa: "ਸ"}, {en: "ਉ", hi: "उ", pa: "ਉ"}, {en: "ਹ", hi: "ह", pa: "ਹ"}], correctAnswer: 2 },
      { question: { en: "Which of these comes last in dictionary order?", hi: "इनमें से कौन सा शब्दकोश क्रम में सबसे अंत में आता है?", pa: "ਇਹਨਾਂ ਵਿੱਚੋਂ ਕਿਹੜਾ ਸ਼ਬਦਕੋਸ਼ ਕ੍ਰਮ ਵਿੱਚ ਸਭ ਤੋਂ ਅਖੀਰ ਵਿੱਚ ਆਉਂਦਾ ਹੈ?" }, options: [{en: "ਪੰਜਾਬ", hi: "पंजाब", pa: "ਪੰਜਾਬ"}, {en: "ਭਾਰਤ", hi: "भारत", pa: "ਭਾਰਤ"}, {en: "ਮੇਜ਼", hi: "मेज़", pa: "ਮੇਜ਼"}, {en: "ਯਾਤਰਾ", hi: "यात्रा", pa: "ਯਾਤਰਾ"}], correctAnswer: 3 },
      { question: { en: "The order of letters in Gurmukhi is called:", hi: "गुरुमुखी में अक्षरों के क्रम को कहा जाता है:", pa: "ਗੁਰਮੁਖੀ ਵਿੱਚ ਅੱਖਰਾਂ ਦੀ ਤਰਤੀਬ ਨੂੰ ਕੀ ਕਿਹਾ ਜਾਂਦਾ ਹੈ:" }, options: [{en: "Painti", hi: "पैंती", pa: "ਪੈਂਤੀ"}, {en: "Varnmala", hi: "वर्णमाला", pa: "ਵਰਣਮਾਲਾ"}, {en: "Akhar", hi: "अक्षर", pa: "ਅੱਖਰ"}, {en: "Shabad", hi: "शब्द", pa: "ਸ਼ਬਦ"}], correctAnswer: 0 },
    ] },
    { id: 'pun-11-3', grade: 11, title: { en: 'Writing Skills: Official Letters', hi: 'लेखन कौशल: आधिकारिक पत्र', pa: 'ਲਿਖਣ ਕਲਾ: ਦਫ਼ਤਰੀ ਪੱਤਰ' }, xp: 60, questions: [
        { question: { en: "What is the correct salutation for an official letter to a principal?", hi: "एक प्रधानाचार्य को आधिकारिक पत्र के लिए सही अभिवादन क्या है?", pa: "ਪ੍ਰਿੰਸੀਪਲ ਨੂੰ ਇੱਕ ਦਫ਼ਤਰੀ ਪੱਤਰ ਲਈ ਸਹੀ ਸੰਬੋਧਨ ਕੀ ਹੈ?" }, options: [{en: "Dear Sir/Madam", hi: "प्रिय महोदय/महोदया", pa: "ਪਿਆਰੇ ਸਰ/ਮੈਡਮ"}, {en: "Respected Sir/Madam", hi: "आदरणीय महोदय/महोदया", pa: "ਸਤਿਕਾਰਯੋਗ ਸਰ/ਮੈਡਮ"}, {en: "My Dear Principal", hi: "मेरे प्रिय प्रधानाचार्य", pa: "ਮੇਰੇ ਪਿਆਰੇ ਪ੍ਰਿੰਸੀਪਲ"}, {en: "Hello", hi: "नमस्ते", pa: "ਹੈਲੋ"}], correctAnswer: 1 },
        { question: { en: "Where is the sender's address placed in an official letter?", hi: "एक आधिकारिक पत्र में प्रेषक का पता कहाँ रखा जाता है?", pa: "ਇੱਕ ਦਫ਼ਤਰੀ ਪੱਤਰ ਵਿੱਚ ਭੇਜਣ ਵਾਲੇ ਦਾ ਪਤਾ ਕਿੱਥੇ ਲਿਖਿਆ ਜਾਂਦਾ ਹੈ?" }, options: [{en: "Top left", hi: "ऊपर बाईं ओर", pa: "ਉੱਪਰ ਖੱਬੇ"}, {en: "Top right", hi: "ऊपर दाईं ओर", pa: "ਉੱਪਰ ਸੱਜੇ"}, {en: "Bottom left", hi: "नीचे बाईं ओर", pa: "ਹੇਠਾਂ ਖੱਬੇ"}, {en: "Bottom right", hi: "नीचे दाईं ओर", pa: "ਹੇਠਾਂ ਸੱਜੇ"}], correctAnswer: 0 },
        { question: { en: "What is the closing of an official letter called?", hi: "एक आधिकारिक पत्र के समापन को क्या कहा जाता है?", pa: "ਇੱਕ ਦਫ਼ਤਰੀ ਪੱਤਰ ਦੀ ਸਮਾਪਤੀ ਨੂੰ ਕੀ ਕਿਹਾ ਜਾਂਦਾ ਹੈ?" }, options: [{en: "Subscription", hi: "अभिदान", pa: "ਸਬਸਕ੍ਰਿਪਸ਼ਨ"}, {en: "Conclusion", hi: "निष्कर्ष", pa: "ਸਿੱਟਾ"}, {en: "Ending", hi: "समापन", pa: "ਅੰਤ"}, {en: "Body", hi: "मुख्य भाग", pa: "ਭਾਗ"}], correctAnswer: 0 },
        { question: { en: "Which of these is a suitable subject for a letter to the Municipal Corporation?", hi: "नगर निगम को पत्र के लिए इनमें से कौन सा एक उपयुक्त विषय है?", pa: "ਨਗਰ ਨਿਗਮ ਨੂੰ ਪੱਤਰ ਲਈ ਇਹਨਾਂ ਵਿੱਚੋਂ ਕਿਹੜਾ ਇੱਕ ਢੁਕਵਾਂ ਵਿਸ਼ਾ ਹੈ?" }, options: [{en: "Invitation to a party", hi: "एक पार्टी में निमंत्रण", pa: "ਇੱਕ ਪਾਰਟੀ ਲਈ ਸੱਦਾ"}, {en: "Poor sanitary conditions", hi: "खराब स्वच्छता की स्थिति", pa: "ਮਾੜੀ ਸਫਾਈ ਦੀ ਹਾਲਤ"}, {en: "Asking for a new book", hi: "एक नई किताब के लिए पूछना", pa: "ਇੱਕ ਨਵੀਂ ਕਿਤਾਬ ਲਈ ਪੁੱਛਣਾ"}, {en: "Holiday plans", hi: "छुट्टियों की योजनाएं", pa: "ਛੁੱਟੀਆਂ ਦੀਆਂ ਯੋਜਨਾਵਾਂ"}], correctAnswer: 1 },
        { question: { en: "The main content of the letter is written in the:", hi: "पत्र की मुख्य सामग्री लिखी जाती है:", pa: "ਪੱਤਰ ਦੀ ਮੁੱਖ ਸਮੱਗਰੀ ਕਿਸ ਵਿੱਚ ਲਿਖੀ ਜਾਂਦੀ ਹੈ:" }, options: [{en: "Salutation", hi: "अभिवादन", pa: "ਸੰਬੋਧਨ"}, {en: "Body", hi: "मुख्य भाग", pa: "ਭਾਗ"}, {en: "Heading", hi: "शीर्षक", pa: "ਸਿਰਲੇਖ"}, {en: "Signature", hi: "हस्ताक्षर", pa: "ਹਸਤਾਖਰ"}], correctAnswer: 1 },
    ] },
    { id: 'pun-12-1', grade: 12, title: { en: 'Modern Punjabi Poetry', hi: 'आधुनिक पंजाबी कविता', pa: 'ਆਧੁਨਿਕ ਪੰਜਾਬੀ ਕਵਿਤਾ' }, xp: 60, questions: [
        { question: { en: "Who is known as the father of modern Punjabi poetry?", hi: "आधुनिक पंजाबी कविता का जनक किसे कहा जाता है?", pa: "ਆਧੁਨਿਕ ਪੰਜਾਬੀ ਕਵਿਤਾ ਦਾ ਪਿਤਾਮਾ ਕਿਸ ਨੂੰ ਕਿਹਾ ਜਾਂਦਾ ਹੈ?" }, options: [{en: "Bhai Vir Singh", hi: "भाई वीर सिंह", pa: "ਭਾਈ ਵੀਰ ਸਿੰਘ"}, {en: "Amrita Pritam", hi: "अमृता प्रीतम", pa: "ਅੰਮ੍ਰਿਤਾ ਪ੍ਰੀਤਮ"}, {en: "Shiv Kumar Batalvi", hi: "शिव कुमार बटालवी", pa: "ਸ਼ਿਵ ਕੁਮਾਰ ਬਟਾਲਵੀ"}], correctAnswer: 0 },
        { question: { en: "Amrita Pritam's famous poem about the partition of India is:", hi: "भारत के विभाजन के बारे में अमृता प्रीतम की प्रसिद्ध कविता है:", pa: "ਭਾਰਤ ਦੀ ਵੰਡ ਬਾਰੇ ਅੰਮ੍ਰਿਤਾ ਪ੍ਰੀਤਮ ਦੀ ਮਸ਼ਹੂਰ ਕਵਿਤਾ ਹੈ:" }, options: [{en: "Ajj Aakhaan Waris Shah Nu", hi: "अज्ज आखां वारिस शाह नूँ", pa: "ਅੱਜ ਆਖਾਂ ਵਾਰਿਸ ਸ਼ਾਹ ਨੂੰ"}, {en: "Sunehade", hi: "सुनेहड़े", pa: "ਸੁਨੇਹੜੇ"}, {en: "Kagaz Te Canvas", hi: "कागज ते कैनवस", pa: "ਕਾਗਜ਼ ਤੇ ਕੈਨਵਸ"}], correctAnswer: 0 },
        { question: { en: "Shiv Kumar Batalvi is often called the 'Birha Da Sultan' which means:", hi: "शिव कुमार बटालवी को अक्सर 'बिरहा दा सुल्तान' कहा जाता है जिसका अर्थ है:", pa: "ਸ਼ਿਵ ਕੁਮਾਰ ਬਟਾਲਵੀ ਨੂੰ ਅਕਸਰ 'ਬਿਰਹਾ ਦਾ ਸੁਲਤਾਨ' ਕਿਹਾ ਜਾਂਦਾ ਹੈ ਜਿਸਦਾ ਮਤਲਬ ਹੈ:" }, options: [{en: "King of Romance", hi: "रोमांस का राजा", pa: "ਰੋਮਾਂਸ ਦਾ ਰਾਜਾ"}, {en: "King of Separation", hi: "जुदाई का राजा", pa: "ਵਿਛੋੜੇ ਦਾ ਰਾਜਾ"}, {en: "King of Nature", hi: "प्रकृति का राजा", pa: "ਕੁਦਰਤ ਦਾ ਰਾਜਾ"}], correctAnswer: 1 },
    ] },
    { id: 'pun-12-2', grade: 12, title: { en: 'Punjabi Novel', hi: 'पंजाबी उपन्यास', pa: 'ਪੰਜਾਬੀ ਨਾਵਲ' }, xp: 60, questions: [
        { question: { en: "Who wrote the first Punjabi novel 'Sundari'?", hi: "'सुंदरी' नामक पहला पंजाबी उपन्यास किसने लिखा?", pa: "'ਸੁੰਦਰੀ' ਨਾਂ ਦਾ ਪਹਿਲਾ ਪੰਜਾਬੀ ਨਾਵਲ ਕਿਸਨੇ ਲਿਖਿਆ?" }, options: [{en: "Nanak Singh", hi: "नानक सिंह", pa: "ਨਾਨਕ ਸਿੰਘ"}, {en: "Bhai Vir Singh", hi: "भाई वीर सिंह", pa: "ਭਾਈ ਵੀਰ ਸਿੰਘ"}, {en: "Gurdial Singh", hi: "गुरदयाल सिंह", pa: "ਗੁਰਦਿਆਲ ਸਿੰਘ"}], correctAnswer: 1 },
        { question: { en: "Nanak Singh is famous for his novels on:", hi: "नानक सिंह अपने उपन्यासों के लिए प्रसिद्ध हैं:", pa: "ਨਾਨਕ ਸਿੰਘ ਆਪਣੇ ਨਾਵਲਾਂ ਲਈ ਮਸ਼ਹੂਰ ਹਨ:" }, options: [{en: "Social reform", hi: "समाज सुधार", pa: "ਸਮਾਜ ਸੁਧਾਰ"}, {en: "Historical events", hi: "ऐतिहासिक घटनाएं", pa: "ਇਤਿਹਾਸਕ ਘਟਨਾਵਾਂ"}, {en: "Mythology", hi: "पौराणिक कथाएं", pa: "ਮਿਥਿਹਾਸ"}], correctAnswer: 0 },
        { question: { en: "'Marhi Da Deeva' is a famous novel by:", hi: "'मढ़ी दा दीवा' किसका प्रसिद्ध उपन्यास है:", pa: "'ਮੜ੍ਹੀ ਦਾ ਦੀਵਾ' ਕਿਸਦਾ ਮਸ਼ਹੂਰ ਨਾਵਲ ਹੈ:" }, options: [{en: "Jaswant Singh Kanwal", hi: "जसवंत सिंह कंवल", pa: "ਜਸਵੰਤ ਸਿੰਘ ਕੰਵਲ"}, {en: "Sohan Singh Sital", hi: "सोहन सिंह सीतल", pa: "ਸੋਹਣ ਸਿੰਘ ਸੀਤਲ"}, {en: "Gurdial Singh", hi: "गुरदयाल सिंह", pa: "ਗੁਰਦਿਆਲ ਸਿੰਘ"}], correctAnswer: 2 },
    ] },
  ],
  math: [
    { id: 'math-11-1', grade: 11, title: { en: 'Sets', hi: 'समुच्चय', pa: 'ਸੈੱਟ' }, xp: 50, questions: [
        { question: { en: "What is the union of sets A = {1, 2} and B = {2, 3}?", hi: "समुच्चय A = {1, 2} और B = {2, 3} का संघ क्या है?", pa: "ਸੈੱਟ A = {1, 2} ਅਤੇ B = {2, 3} ਦਾ ਯੂਨੀਅਨ ਕੀ ਹੈ?" }, options: [{en: "{1, 2, 3}", hi: "{1, 2, 3}", pa: "{1, 2, 3}"}, {en: "{2}", hi: "{2}", pa: "{2}"}, {en: "{1, 3}", hi: "{1, 3}", pa: "{1, 3}"}], correctAnswer: 0 },
        { question: { en: "What is the intersection of sets A = {1, 2, 3} and B = {3, 4, 5}?", hi: "समुच्चय A = {1, 2, 3} और B = {3, 4, 5} का प्रतिच्छेदन क्या है?", pa: "ਸੈੱਟ A = {1, 2, 3} ਅਤੇ B = {3, 4, 5} ਦਾ ਇੰਟਰਸੈਕਸ਼ਨ ਕੀ ਹੈ?" }, options: [{en: "{1, 2, 3, 4, 5}", hi: "{1, 2, 3, 4, 5}", pa: "{1, 2, 3, 4, 5}"}, {en: "{3}", hi: "{3}", pa: "{3}"}, {en: "{}", hi: "{}", pa: "{}"}], correctAnswer: 1 },
        { question: { en: "If a set has n elements, how many subsets does it have?", hi: "यदि एक समुच्चय में n अवयव हैं, तो उसके कितने उपसमुच्चय होते हैं?", pa: "ਜੇ ਇੱਕ ਸੈੱਟ ਵਿੱਚ n ਐਲੀਮੈਂਟਸ ਹਨ, ਤਾਂ ਇਸਦੇ ਕਿੰਨੇ ਸਬਸੈੱਟ ਹੁੰਦੇ ਹਨ?" }, options: [{en: "n", hi: "n", pa: "n"}, {en: "2n", hi: "2n", pa: "2n"}, {en: "2^n", hi: "2^n", pa: "2^n"}], correctAnswer: 2 },
    ] },
    { id: 'math-11-2', grade: 11, title: { en: 'Relations & Functions', hi: 'संबंध और फलन', pa: 'ਸੰਬੰਧ ਅਤੇ ਫੰਕਸ਼ਨ' }, xp: 75, questions: [
        { question: { en: "If f(x) = 2x + 5, what is f(3)?", hi: "यदि f(x) = 2x + 5, तो f(3) क्या है?", pa: "ਜੇਕਰ f(x) = 2x + 5, ਤਾਂ f(3) ਕੀ ਹੈ?" }, options: [{en: "8", hi: "8", pa: "8"}, {en: "10", hi: "10", pa: "10"}, {en: "11", hi: "11", pa: "11"}], correctAnswer: 2 },
        { question: { en: "The set of all first elements of the ordered pairs in a relation R is called the:", hi: "एक संबंध R में क्रमित युग्मों के सभी पहले तत्वों के समुच्चय को कहा जाता है:", pa: "ਇੱਕ ਰਿਲੇਸ਼ਨ R ਵਿੱਚ ਕ੍ਰਮਬੱਧ ਜੋੜਿਆਂ ਦੇ ਸਾਰੇ ਪਹਿਲੇ ਐਲੀਮੈਂਟਸ ਦੇ ਸੈੱਟ ਨੂੰ ਕੀ ਕਿਹਾ ਜਾਂਦਾ ਹੈ:" }, options: [{en: "Range", hi: "परिसर", pa: "ਰੇਂਜ"}, {en: "Domain", hi: "प्रांत", pa: "ਡੋਮੇਨ"}, {en: "Co-domain", hi: "सह-प्रांत", pa: "ਕੋ-ਡੋਮੇਨ"}], correctAnswer: 1 },
        { question: { en: "A relation where each element of the domain is related to exactly one element of the range is called a:", hi: "एक संबंध जिसमें प्रांत का प्रत्येक अवयव परिसर के ठीक एक अवयव से संबंधित होता है, कहलाता है:", pa: "ਇੱਕ ਰਿਲੇਸ਼ਨ ਜਿਸ ਵਿੱਚ ਡੋਮੇਨ ਦਾ ਹਰੇਕ ਐਲੀਮੈਂਟ ਰੇਂਜ ਦੇ ਸਿਰਫ ਇੱਕ ਐਲੀਮੈਂਟ ਨਾਲ ਸਬੰਧਤ ਹੁੰਦਾ ਹੈ, ਨੂੰ ਕੀ ਕਿਹਾ ਜਾਂਦਾ ਹੈ:" }, options: [{en: "Set", hi: "समुच्चय", pa: "ਸੈੱਟ"}, {en: "Function", hi: "फलन", pa: "ਫੰਕਸ਼ਨ"}, {en: "Relation", hi: "संबंध", pa: "ਰਿਲੇਸ਼ਨ"}], correctAnswer: 1 },
    ] },
    { id: 'math-11-3', grade: 11, title: { en: 'Trigonometric Functions', hi: 'त्रिकोणमितीय फलन', pa: 'ਤਿਕੋਣਮਿਤੀ ਫੰਕਸ਼ਨ' }, xp: 80, questions: [
        { question: { en: "What is the value of sin^2(x) + cos^2(x)?", hi: "sin^2(x) + cos^2(x) का मान क्या है?", pa: "sin^2(x) + cos^2(x) ਦਾ ਮੁੱਲ ਕੀ ਹੈ?" }, options: [{en: "0", hi: "0", pa: "0"}, {en: "1", hi: "1", pa: "1"}, {en: "2", hi: "2", pa: "2"}], correctAnswer: 1 },
        { question: { en: "How many degrees is π radians?", hi: "π रेडियन कितने डिग्री के बराबर होता है?", pa: "π ਰੇਡੀਅਨ ਕਿੰਨੇ ਡਿਗਰੀ ਦੇ ਬਰਾਬਰ ਹੁੰਦਾ ਹੈ?" }, options: [{en: "90°", hi: "90°", pa: "90°"}, {en: "180°", hi: "180°", pa: "180°"}, {en: "360°", hi: "360°", pa: "360°"}], correctAnswer: 1 },
        { question: { en: "What is the value of tan(45°)?", hi: "tan(45°) का मान क्या है?", pa: "tan(45°) ਦਾ ਮੁੱਲ ਕੀ ਹੈ?" }, options: [{en: "0", hi: "0", pa: "0"}, {en: "1", hi: "1", pa: "1"}, {en: "undefined", hi: "अपरिभाषित", pa: "ਪਰਿਭਾਸ਼ਿਤ ਨਹੀਂ"}], correctAnswer: 1 },
    ] },
    { id: 'math-12-1', grade: 12, title: { en: 'Matrices', hi: 'आव्यूह', pa: 'ਮੈਟ੍ਰਿਕਸ' }, xp: 60, questions: [
        { question: { en: "A matrix with the same number of rows and columns is called a:", hi: "एक आव्यूह जिसमें पंक्तियों और स्तंभों की संख्या समान हो, कहलाता है:", pa: "ਇੱਕ ਮੈਟ੍ਰਿਕਸ ਜਿਸ ਵਿੱਚ ਕਤਾਰਾਂ ਅਤੇ ਕਾਲਮਾਂ ਦੀ ਗਿਣਤੀ ਬਰਾਬਰ ਹੁੰਦੀ ਹੈ, ਨੂੰ ਕੀ ਕਿਹਾ ਜਾਂਦਾ ਹੈ:" }, options: [{en: "Row matrix", hi: "पंक्ति आव्यूह", pa: "ਕਤਾਰ ਮੈਟ੍ਰਿਕਸ"}, {en: "Square matrix", hi: "वर्ग आव्यूह", pa: "ਵਰਗ ਮੈਟ੍ਰਿਕਸ"}, {en: "Null matrix", hi: "शून्य आव्यूह", pa: "ਨਲ ਮੈਟ੍ਰਿਕਸ"}], correctAnswer: 1 },
        { question: { en: "If A is a 2x3 matrix and B is a 3x4 matrix, what is the order of the product AB?", hi: "यदि A एक 2x3 आव्यूह है और B एक 3x4 आव्यूह है, तो गुणनफल AB का क्रम क्या है?", pa: "ਜੇਕਰ A ਇੱਕ 2x3 ਮੈਟ੍ਰਿਕਸ ਹੈ ਅਤੇ B ਇੱਕ 3x4 ਮੈਟ੍ਰਿਕਸ ਹੈ, ਤਾਂ ਗੁਣਨਫਲ AB ਦਾ ਕ੍ਰਮ ਕੀ ਹੈ?" }, options: [{en: "3x2", hi: "3x2", pa: "3x2"}, {en: "2x4", hi: "2x4", pa: "2x4"}, {en: "4x2", hi: "4x2", pa: "4x2"}], correctAnswer: 1 },
        { question: { en: "The transpose of a matrix is obtained by:", hi: "एक आव्यूह का परिवर्त प्राप्त किया जाता है:", pa: "ਇੱਕ ਮੈਟ੍ਰਿਕਸ ਦਾ ਟ੍ਰਾਂਸਪੋਜ਼ ਕਿਵੇਂ ਪ੍ਰਾਪਤ ਕੀਤਾ ਜਾਂਦਾ ਹੈ:" }, options: [{en: "Interchanging rows and columns", hi: "पंक्तियों और स्तंभों को आपस में बदलकर", pa: "ਕਤਾਰਾਂ ਅਤੇ ਕਾਲਮਾਂ ਨੂੰ ਆਪਸ ਵਿੱਚ ਬਦਲ ਕੇ"}, {en: "Multiplying by -1", hi: "-1 से गुणा करके", pa: "-1 ਨਾਲ ਗੁਣਾ ਕਰਕੇ"}, {en: "Finding the determinant", hi: "सारणिक ज्ञात करके", pa: "ਨਿਰਧਾਰਕ ਲੱਭ ਕੇ"}], correctAnswer: 0 },
    ] },
    { id: 'math-12-2', grade: 12, title: { en: 'Determinants', hi: 'सारणिक', pa: 'ਨਿਰਧਾਰਕ' }, xp: 60, questions: [
        { question: { en: "If two rows of a determinant are identical, the value of the determinant is:", hi: "यदि किसी सारणिक की दो पंक्तियाँ समान हों, तो सारणिक का मान होता है:", pa: "ਜੇਕਰ ਇੱਕ ਨਿਰਧਾਰਕ ਦੀਆਂ ਦੋ ਕਤਾਰਾਂ ਇੱਕੋ ਜਿਹੀਆਂ ਹੋਣ, ਤਾਂ ਨਿਰਧਾਰਕ ਦਾ ਮੁੱਲ ਹੁੰਦਾ ਹੈ:" }, options: [{en: "1", hi: "1", pa: "1"}, {en: "0", hi: "0", pa: "0"}, {en: "-1", hi: "-1", pa: "-1"}], correctAnswer: 1 },
        { question: { en: "The determinant of an identity matrix is always:", hi: "एक तत्समक आव्यूह का सारणिक हमेशा होता है:", pa: "ਇੱਕ ਪਛਾਣ ਮੈਟ੍ਰਿਕਸ ਦਾ ਨਿਰਧਾਰਕ ਹਮੇਸ਼ਾ ਹੁੰਦਾ ਹੈ:" }, options: [{en: "0", hi: "0", pa: "0"}, {en: "1", hi: "1", pa: "1"}, {en: "Depends on order", hi: "क्रम पर निर्भर करता है", pa: "ਕ੍ਰਮ 'ਤੇ ਨਿਰਭਰ ਕਰਦਾ ਹੈ"}], correctAnswer: 1 },
        { question: { en: "A square matrix A is invertible if and only if its determinant is:", hi: "एक वर्ग आव्यूह A व्युत्क्रमणीय होता है यदि और केवल यदि उसका सारणिक है:", pa: "ਇੱਕ ਵਰਗ ਮੈਟ੍ਰਿਕਸ A ਉਲਟਾਉਣਯੋਗ ਹੁੰਦਾ ਹੈ ਜੇਕਰ ਅਤੇ ਕੇਵਲ ਜੇਕਰ ਇਸਦਾ ਨਿਰਧਾਰਕ ਹੈ:" }, options: [{en: "Zero", hi: "शून्य", pa: "ਜ਼ੀਰੋ"}, {en: "Non-zero", hi: "गैर-शून्य", pa: "ਗੈਰ-ਜ਼ੀਰੋ"}, {en: "Positive", hi: "धनात्मक", pa: "ਸਕਾਰਾਤਮਕ"}], correctAnswer: 1 },
    ] },
     { id: 'math-12-3', grade: 12, title: { en: 'Continuity and Differentiability', hi: 'सांतत्य तथा अवकलनीयता', pa: 'ਨਿਰੰਤਰਤਾ ਅਤੇ ਵਿਭਿੰਨਤਾ' }, xp: 80, questions: [
        { question: { en: "A function is continuous at a point if the limit at that point:", hi: "एक फलन किसी बिंदु पर संतत होता है यदि उस बिंदु पर सीमा:", pa: "ਇੱਕ ਫੰਕਸ਼ਨ ਇੱਕ ਬਿੰਦੂ 'ਤੇ ਨਿਰੰਤਰ ਹੁੰਦਾ ਹੈ ਜੇਕਰ ਉਸ ਬਿੰਦੂ 'ਤੇ ਸੀਮਾ:" }, options: [{en: "Exists", hi: "मौजूद है", pa: "ਮੌਜੂਦ ਹੈ"}, {en: "Equals the function value", hi: "फलन मान के बराबर है", pa: "ਫੰਕਸ਼ਨ ਮੁੱਲ ਦੇ ਬਰਾਬਰ ਹੈ"}, {en: "Is zero", hi: "शून्य है", pa: "ਜ਼ੀਰੋ ਹੈ"}], correctAnswer: 1 },
        { question: { en: "What is the derivative of x^n?", hi: "x^n का अवकलज क्या है?", pa: "x^n ਦਾ ਡੈਰੀਵੇਟਿਵ ਕੀ ਹੈ?" }, options: [{en: "n*x^(n-1)", hi: "n*x^(n-1)", pa: "n*x^(n-1)"}, {en: "x^n / n", hi: "x^n / n", pa: "x^n / n"}, {en: "n*x^n", hi: "n*x^n", pa: "n*x^n"}], correctAnswer: 0 },
        { question: { en: "The derivative of a constant function is:", hi: "एक अचर फलन का अवकलज है:", pa: "ਇੱਕ ਸਥਿਰ ਫੰਕਸ਼ਨ ਦਾ ਡੈਰੀਵੇਟਿਵ ਹੈ:" }, options: [{en: "1", hi: "1", pa: "1"}, {en: "The constant itself", hi: "स्वयं अचर", pa: "ਸਥਿਰ ਖੁਦ"}, {en: "0", hi: "0", pa: "0"}], correctAnswer: 2 },
    ] },
    { id: 'math-12-4', grade: 12, title: { en: 'Integrals', hi: 'समाकलन', pa: 'ਇੰਟੈਗਰਲ' }, xp: 80, questions: [
        { question: { en: "Integration is the reverse process of:", hi: "समाकलन किसकी उल्टी प्रक्रिया है:", pa: "ਏਕੀਕਰਣ ਕਿਸ ਦੀ ਉਲਟ ਪ੍ਰਕਿਰਿਆ ਹੈ:" }, options: [{en: "Differentiation", hi: "अवकलन", pa: "ਵਿਭਿੰਨਤਾ"}, {en: "Limits", hi: "सीमा", pa: "ਸੀਮਾਵਾਂ"}, {en: "Addition", hi: "जोड़", pa: "ਜੋੜ"}], correctAnswer: 0 },
        { question: { en: "What is the integral of 1 with respect to x?", hi: "x के सापेक्ष 1 का समाकलन क्या है?", pa: "x ਦੇ ਸਬੰਧ ਵਿੱਚ 1 ਦਾ ਇੰਟੈਗਰਲ ਕੀ ਹੈ?" }, options: [{en: "0", hi: "0", pa: "0"}, {en: "x + C", hi: "x + C", pa: "x + C"}, {en: "1", hi: "1", pa: "1"}], correctAnswer: 1 },
        { question: { en: "A definite integral has:", hi: "एक निश्चित समाकलन में होता है:", pa: "ਇੱਕ ਨਿਸ਼ਚਿਤ ਇੰਟੈਗਰਲ ਵਿੱਚ ਹੁੰਦਾ ਹੈ:" }, options: [{en: "A constant of integration", hi: "समाकलन का एक स्थिरांक", pa: "ਏਕੀਕਰਣ ਦਾ ਇੱਕ ਸਥਿਰ"}, {en: "Upper and lower limits", hi: "ऊपरी और निचली सीमाएं", pa: "ਉੱਪਰ ਅਤੇ ਹੇਠਲੀਆਂ ਸੀਮਾਵਾਂ"}, {en: "No solution", hi: "कोई हल नहीं", pa: "ਕੋਈ ਹੱਲ ਨਹੀਂ"}], correctAnswer: 1 },
    ] },
    { id: 'math-12-5', grade: 12, title: { en: 'Probability', hi: 'प्रायिकता', pa: 'ਸੰਭਾਵਨਾ' }, xp: 70, questions: [
      { question: { en: "What is the probability of getting a head when a coin is tossed?", hi: "एक सिक्का उछालने पर चित आने की प्रायिकता क्या है?", pa: "ਇੱਕ ਸਿੱਕਾ ਉਛਾਲਣ 'ਤੇ ਹੈੱਡ ਆਉਣ ਦੀ ਸੰਭਾਵਨਾ ਕੀ ਹੈ?" }, options: [{en: "0", hi: "0", pa: "0"}, {en: "1/2", hi: "1/2", pa: "1/2"}, {en: "1", hi: "1", pa: "1"}], correctAnswer: 1 },
      { question: { en: "The probability of an event always lies between:", hi: "किसी घटना की प्रायिकता हमेशा किसके बीच होती है:", pa: "ਕਿਸੇ ਘਟਨਾ ਦੀ ਸੰਭਾਵਨਾ ਹਮੇਸ਼ਾ ਕਿਸ ਦੇ ਵਿਚਕਾਰ ਹੁੰਦੀ ਹੈ:" }, options: [{en: "0 and 1", hi: "0 और 1", pa: "0 ਅਤੇ 1"}, {en: "-1 and 1", hi: "-1 और 1", pa: "-1 ਅਤੇ 1"}, {en: "0 and infinity", hi: "0 और अनंत", pa: "0 ਅਤੇ ਅਨੰਤ"}], correctAnswer: 0 },
      { question: { en: "If P(A) = 0.3, what is P(not A)?", hi: "यदि P(A) = 0.3, तो P(A नहीं) क्या है?", pa: "ਜੇਕਰ P(A) = 0.3, ਤਾਂ P(not A) ਕੀ ਹੈ?" }, options: [{en: "0.3", hi: "0.3", pa: "0.3"}, {en: "0.7", hi: "0.7", pa: "0.7"}, {en: "1", hi: "1", pa: "1"}], correctAnswer: 1 },
    ] },
  ],
  physics: [
      { id: 'phy-11-1', grade: 11, title: { en: 'Units and Measurements', hi: 'मात्रक और मापन', pa: 'ਇਕਾਈਆਂ ਅਤੇ ਮਾਪ' }, xp: 50, questions: [
        { question: { en: "What is the SI unit for mass?", hi: "द्रव्यमान का SI मात्रक क्या है?", pa: "ਪੁੰਜ ਦੀ SI ਇਕਾਈ ਕੀ ਹੈ?" }, options: [{en: "Meter", hi: "मीटर", pa: "ਮੀਟਰ"}, {en: "Kilogram", hi: "किलोग्राम", pa: "ਕਿਲੋਗ੍ਰਾਮ"}, {en: "Second", hi: "सेकंड", pa: "ਸਕਿੰਟ"}], correctAnswer: 1 },
        { question: { en: "Which of these is a fundamental quantity?", hi: "इनमें से कौन सी एक मौलिक राशि है?", pa: "ਇਹਨਾਂ ਵਿੱਚੋਂ ਕਿਹੜੀ ਇੱਕ ਬੁਨਿਆਦੀ ਮਾਤਰਾ ਹੈ?" }, options: [{en: "Velocity", hi: "वेग", pa: "ਵੇਗ"}, {en: "Force", hi: "बल", pa: "ਬਲ"}, {en: "Time", hi: "समय", pa: "ਸਮਾਂ"}], correctAnswer: 2 },
        { question: { en: "What is the dimensional formula for Velocity?", hi: "वेग का आयामी सूत्र क्या है?", pa: "ਵੇਗ ਦਾ ਅਯਾਮੀ ਫਾਰਮੂਲਾ ਕੀ ਹੈ?" }, options: [{en: "[LT^-1]", hi: "[LT^-1]", pa: "[LT^-1]"}, {en: "[LT^-2]", hi: "[LT^-2]", pa: "[LT^-2]"}, {en: "[MLT^-2]", hi: "[MLT^-2]", pa: "[MLT^-2]"}], correctAnswer: 0 },
      ] },
      { id: 'phy-11-2', grade: 11, title: { en: 'Laws of Motion', hi: 'गति के नियम', pa: 'ਗਤੀ ਦੇ ਨਿਯਮ' }, xp: 70, questions: [
        { question: { en: "Newton's first law of motion is also known as the law of:", hi: "न्यूटन के गति के पहले नियम को इस नाम से भी जाना जाता है:", pa: "ਨਿਊਟਨ ਦੇ ਗਤੀ ਦੇ ਪਹਿਲੇ ਨਿਯਮ ਨੂੰ ਇਸ ਨਾਮ ਨਾਲ ਵੀ ਜਾਣਿਆ ਜਾਂਦਾ ਹੈ:" }, options: [{en: "Action-Reaction", hi: "क्रिया-प्रतिक्रिया", pa: "ਕਿਰਿਆ-ਪ੍ਰਤੀਕਿਰਿਆ"}, {en: "Inertia", hi: "जड़ता", pa: "ਜੜਤਾ"}, {en: "Acceleration", hi: "त्वरण", pa: "ਪ੍ਰਵੇਗ"}], correctAnswer: 1 },
        { question: { en: "Force is defined as the product of mass and:", hi: "बल को द्रव्यमान और किसके गुणनफल के रूप में परिभाषित किया गया है:", pa: "ਬਲ ਨੂੰ ਪੁੰਜ ਅਤੇ ਕਿਸ ਦੇ ਗੁਣਨਫਲ ਵਜੋਂ ਪਰਿਭਾਸ਼ਿਤ ਕੀਤਾ ਗਿਆ ਹੈ:" }, options: [{en: "Velocity", hi: "वेग", pa: "ਵੇਗ"}, {en: "Displacement", hi: "विस्थापन", pa: "ਵਿਸਥਾਪਨ"}, {en: "Acceleration", hi: "त्वरण", pa: "ਪ੍ਰਵੇਗ"}], correctAnswer: 2 },
        { question: { en: "For every action, there is an equal and opposite reaction. This is Newton's:", hi: "प्रत्येक क्रिया के लिए, एक समान और विपरीत प्रतिक्रिया होती है। यह न्यूटन का:", pa: "ਹਰ ਕਿਰਿਆ ਲਈ, ਇੱਕ ਬਰਾਬਰ ਅਤੇ ਉਲਟ ਪ੍ਰਤੀਕਿਰਿਆ ਹੁੰਦੀ ਹੈ। ਇਹ ਨਿਊਟਨ ਦਾ:" }, options: [{en: "First Law", hi: "पहला नियम", pa: "ਪਹਿਲਾ ਨਿਯਮ"}, {en: "Second Law", hi: "दूसरा नियम", pa: "ਦੂਜਾ ਨਿਯਮ"}, {en: "Third Law", hi: "तीसरा नियम", pa: "ਤੀਜਾ ਨਿਯਮ"}], correctAnswer: 2 },
      ] },
    { id: 'phy-12-1', grade: 12, title: { en: 'Electrostatics', hi: 'स्थिरवैद्युतिकी', pa: 'ਇਲੈਕਟ੍ਰੋਸਟੈਟਿਕਸ' }, xp: 60, questions: [
        { question: { en: "The law that governs the force between two electric charges is:", hi: "दो विद्युत आवेशों के बीच बल को नियंत्रित करने वाला नियम है:", pa: "ਦੋ ਬਿਜਲਈ ਚਾਰਜਾਂ ਵਿਚਕਾਰ ਬਲ ਨੂੰ ਨਿਯੰਤਰਿਤ ਕਰਨ ਵਾਲਾ ਨਿਯਮ ਹੈ:" }, options: [{en: "Ohm's Law", hi: "ओम का नियम", pa: "ਓਮ ਦਾ ਨਿਯਮ"}, {en: "Coulomb's Law", hi: "कूलम्ब का नियम", pa: "ਕੂਲੰਬ ਦਾ ਨਿਯਮ"}, {en: "Gauss's Law", hi: "गॉस का नियम", pa: "ਗੌਸ ਦਾ ਨਿਯਮ"}], correctAnswer: 1 },
        { question: { en: "The SI unit of electric charge is:", hi: "विद्युत आवेश का SI मात्रक है:", pa: "ਬਿਜਲਈ ਚਾਰਜ ਦੀ SI ਇਕਾਈ ਹੈ:" }, options: [{en: "Volt", hi: "वोल्ट", pa: "ਵੋਲਟ"}, {en: "Ampere", hi: "एम्पीयर", pa: "ਐਂਪੀਅਰ"}, {en: "Coulomb", hi: "कूलम्ब", pa: "ਕੂਲੰਬ"}], correctAnswer: 2 },
        { question: { en: "A device used to store electric charge is a:", hi: "विद्युत आवेश को संग्रहीत करने के लिए उपयोग किया जाने वाला एक उपकरण है:", pa: "ਬਿਜਲਈ ਚਾਰਜ ਨੂੰ ਸਟੋਰ ਕਰਨ ਲਈ ਵਰਤਿਆ ਜਾਣ ਵਾਲਾ ਇੱਕ ਯੰਤਰ ਹੈ:" }, options: [{en: "Resistor", hi: "प्रतिरोधक", pa: "ਰੋਧਕ"}, {en: "Capacitor", hi: "संधारित्र", pa: "ਕੈਪੇਸੀਟਰ"}, {en: "Inductor", hi: "प्रिया", pa: "ਇੰਡਕਟਰ"}], correctAnswer: 1 },
    ] },
    { id: 'phy-12-2', grade: 12, title: { en: 'Current Electricity', hi: 'धारा विद्युत', pa: 'ਕਰੰਟ ਬਿਜਲੀ' }, xp: 60, questions: [
        { question: { en: "Ohm's law gives a relation between:", hi: "ओम का नियम किसके बीच संबंध बताता है:", pa: "ਓਮ ਦਾ ਨਿਯਮ ਕਿਸ ਦੇ ਵਿਚਕਾਰ ਸਬੰਧ ਦੱਸਦਾ ਹੈ:" }, options: [{en: "Voltage and Current", hi: "वोल्टेज और धारा", pa: "ਵੋਲਟੇਜ ਅਤੇ ਕਰੰਟ"}, {en: "Current and Resistance", hi: "धारा और प्रतिरोध", pa: "ਕਰੰਟ ਅਤੇ ਪ੍ਰਤੀਰੋਧ"}, {en: "Voltage, Current and Resistance", hi: "वोल्टेज, धारा और प्रतिरोध", pa: "ਵੋਲਟੇਜ, ਕਰੰਟ ਅਤੇ ਪ੍ਰਤੀਰੋਧ"}], correctAnswer: 2 },
        { question: { en: "The SI unit of resistance is:", hi: "प्रतिरोध का SI मात्रक है:", pa: "ਪ੍ਰਤੀਰੋਧ ਦੀ SI ਇਕਾਈ ਹੈ:" }, options: [{en: "Ohm", hi: "ओम", pa: "ਓਮ"}, {en: "Volt", hi: "वोल्ट", pa: "ਵੋਲਟ"}, {en: "Ampere", hi: "एम्पीयर", pa: "ਐਂਪੀਅਰ"}], correctAnswer: 0 },
        { question: { en: "Kirchhoff's junction rule is based on the conservation of:", hi: "किरचॉफ का संधि नियम किसके संरक्षण पर आधारित है:", pa: "ਕਿਰਚੌਫ ਦਾ ਜੰਕਸ਼ਨ ਨਿਯਮ ਕਿਸ ਦੀ ਸਾਂਭ-ਸੰਭਾਲ 'ਤੇ ਅਧਾਰਤ ਹੈ:" }, options: [{en: "Energy", hi: "ऊर्जा", pa: "ਊਰਜਾ"}, {en: "Momentum", hi: "संवेग", pa: "ਗਤੀ"}, {en: "Charge", hi: "आवेश", pa: "ਚਾਰਜ"}], correctAnswer: 2 },
    ] },
    { id: 'phy-12-3', grade: 12, title: { en: 'Magnetic Effects of Current', hi: 'धारा के चुंबकीय प्रभाव', pa: 'ਕਰੰਟ ਦੇ ਚੁੰਬਕੀ ਪ੍ਰਭਾਵ' }, xp: 70, questions: [
        { question: { en: "A magnetic field can be produced by:", hi: "एक चुंबकीय क्षेत्र उत्पन्न किया जा सकता है:", pa: "ਇੱਕ ਚੁੰਬਕੀ ਖੇਤਰ ਪੈਦਾ ਕੀਤਾ ਜਾ ਸਕਦਾ ਹੈ:" }, options: [{en: "A moving charge", hi: "एक गतिमान आवेश", pa: "ਇੱਕ ਚਲਦਾ ਚਾਰਜ"}, {en: "A stationary charge", hi: "एक स्थिर आवेश", pa: "ਇੱਕ ਸਥਿਰ ਚਾਰਜ"}, {en: "A conductor", hi: "एक चालक", pa: "ਇੱਕ ਕੰਡਕਟਰ"}], correctAnswer: 0 },
        { question: { en: "The force on a moving charge in a magnetic field is given by:", hi: "एक चुंबकीय क्षेत्र में गतिमान आवेश पर लगने वाला बल किसके द्वारा दिया जाता है:", pa: "ਇੱਕ ਚੁੰਬਕੀ ਖੇਤਰ ਵਿੱਚ ਇੱਕ ਚਲਦੇ ਚਾਰਜ 'ਤੇ ਬਲ ਕਿਸ ਦੁਆਰਾ ਦਿੱਤਾ ਜਾਂਦਾ ਹੈ:" }, options: [{en: "Coulomb's Law", hi: "कूलम्ब का नियम", pa: "ਕੂਲੰਬ ਦਾ ਨਿਯਮ"}, {en: "Ohm's Law", hi: "ओम का नियम", pa: "ਓਮ ਦਾ ਨਿਯਮ"}, {en: "Lorentz Force", hi: "लोरेंत्ज़ बल", pa: "ਲੋਰੇਂਟਜ਼ ਬਲ"}], correctAnswer: 2 },
        { question: { en: "The SI unit of magnetic field strength is:", hi: "चुंबकीय क्षेत्र की शक्ति का SI मात्रक है:", pa: "ਚੁੰਬਕੀ ਖੇਤਰ ਦੀ ਤਾਕਤ ਦੀ SI ਇਕਾਈ ਹੈ:" }, options: [{en: "Tesla", hi: "टेस्ला", pa: "ਟੈਸਲਾ"}, {en: "Weber", hi: "वेबर", pa: "ਵੇਬਰ"}, {en: "Henry", hi: "हेनरी", pa: "ਹੈਨਰੀ"}], correctAnswer: 0 },
    ] },
    { id: 'phy-12-4', grade: 12, title: { en: 'Electromagnetic Induction', hi: 'विद्युत चुम्बकीय प्रेरण', pa: 'ਇਲੈਕਟ੍ਰੋਮੈਗਨੈਟਿਕ ਇੰਡਕਸ਼ਨ' }, xp: 70, questions: [
        { question: { en: "The phenomenon of producing an induced EMF in a coil due to a change in magnetic flux is called:", hi: "चुंबकीय प्रवाह में परिवर्तन के कारण एक कुंडली में प्रेरित EMF उत्पन्न करने की घटना को कहा जाता है:", pa: "ਚੁੰਬਕੀ ਪ੍ਰਵਾਹ ਵਿੱਚ ਤਬਦੀਲੀ ਕਾਰਨ ਇੱਕ ਕੋਇਲ ਵਿੱਚ ਇੱਕ ਪ੍ਰੇਰਿਤ EMF ਪੈਦਾ ਕਰਨ ਦੀ ਘਟਨਾ ਨੂੰ ਕੀ ਕਿਹਾ ਜਾਂਦਾ ਹੈ:" }, options: [{en: "Electrolysis", hi: "विद्युतपघटन", pa: "ਇਲੈਕਟ੍ਰੋਲਾਈਸਿਸ"}, {en: "Electromagnetic Induction", hi: "विद्युत चुम्बकीय प्रेरण", pa: "ਇਲੈਕਟ੍ਰੋਮੈਗਨੈਟਿਕ ਇੰਡਕਸ਼ਨ"}, {en: "Self-Induction", hi: "स्वप्रेरण", pa: "ਸਵੈ-ਇੰਡਕਸ਼ਨ"}], correctAnswer: 1 },
        { question: { en: "Lenz's law is a consequence of the law of conservation of:", hi: "लेन्ज का नियम किसके संरक्षण के नियम का परिणाम है:", pa: "ਲੈਂਜ਼ ਦਾ ਨਿਯਮ ਕਿਸ ਦੀ ਸਾਂਭ-ਸੰਭਾਲ ਦੇ ਨਿਯਮ ਦਾ ਨਤੀਜਾ ਹੈ:" }, options: [{en: "Charge", hi: "आवेश", pa: "ਚਾਰਜ"}, {en: "Mass", hi: "द्रव्यमान", pa: "ਪੁੰਜ"}, {en: "Energy", hi: "ऊर्जा", pa: "ਊਰਜਾ"}], correctAnswer: 2 },
        { question: { en: "The SI unit of magnetic flux is:", hi: "चुंबकीय प्रवाह का SI मात्रक है:", pa: "ਚੁੰਬਕੀ ਪ੍ਰਵਾਹ ਦੀ SI ਇਕਾਈ ਹੈ:" }, options: [{en: "Weber", hi: "वेबर", pa: "ਵੇਬਰ"}, {en: "Tesla", hi: "टेस्ला", pa: "ਟੈਸਲਾ"}, {en: "Farad", hi: "फैराड", pa: "ਫੈਰਾਡ"}], correctAnswer: 0 },
    ] },
    { id: 'phy-12-5', grade: 12, title: { en: 'Optics', hi: 'प्रकाशिकी', pa: 'ਆਪਟਿਕਸ' }, xp: 80, questions: [
        { question: { en: "The phenomenon of light bending as it passes from one medium to another is called:", hi: "प्रकाश के एक माध्यम से दूसरे माध्यम में जाने पर मुड़ने की घटना कहलाती है:", pa: "ਪ੍ਰਕਾਸ਼ ਦੇ ਇੱਕ ਮਾਧਿਅਮ ਤੋਂ ਦੂਜੇ ਮਾਧਿਅਮ ਵਿੱਚ ਜਾਣ 'ਤੇ ਝੁਕਣ ਦੀ ਘਟਨਾ ਨੂੰ ਕੀ ਕਿਹਾ ਜਾਂਦਾ ਹੈ:" }, options: [{en: "Reflection", hi: "परावर्तन", pa: "ਪ੍ਰਤੀਬਿੰਬ"}, {en: "Refraction", hi: "अपवर्तन", pa: "ਅਪਵਰਤਨ"}, {en: "Diffraction", hi: "विवर्तन", pa: "ਵਿਵਰਤਨ"}], correctAnswer: 1 },
        { question: { en: "A concave lens always forms a:", hi: "एक अवतल लेंस हमेशा बनाता है:", pa: "ਇੱਕ ਅਵਤਲ ਲੈਂਜ਼ ਹਮੇਸ਼ਾ ਬਣਾਉਂਦਾ ਹੈ:" }, options: [{en: "Real, inverted image", hi: "वास्तविक, उल्टा प्रतिबिंब", pa: "ਅਸਲ, ਉਲਟਾ ਚਿੱਤਰ"}, {en: "Virtual, erect image", hi: "आभासी, सीधा प्रतिबिंब", pa: "ਵਰਚੁਅਲ, ਸਿੱਧਾ ਚਿੱਤਰ"}, {en: "Real, erect image", hi: "वास्तविक, सीधा प्रतिबिंब", pa: "ਅਸਲ, ਸਿੱਧਾ ਚਿੱਤਰ"}], correctAnswer: 1 },
        { question: { en: "The splitting of white light into its constituent colors is called:", hi: "श्वेत प्रकाश का अपने घटक रंगों में विभाजित होना कहलाता है:", pa: "ਚਿੱਟੇ ਪ੍ਰਕਾਸ਼ ਦਾ ਆਪਣੇ ਸੰਘਟਕ ਰੰਗਾਂ ਵਿੱਚ ਵੰਡਿਆ ਜਾਣਾ ਕੀ ਕਹਾਉਂਦਾ ਹੈ:" }, options: [{en: "Dispersion", hi: "विक्षेपण", pa: "ਖਿੰਡਾਅ"}, {en: "Scattering", hi: "प्रकीर्णन", pa: "ਖਿਲਾਰਨਾ"}, {en: "Polarization", hi: "ध्रुवीकरण", pa: "ਧਰੁਵੀਕਰਨ"}], correctAnswer: 0 },
    ] },
  ],
  chemistry: [
      { id: 'chem-11-1', grade: 11, title: { en: 'Basic Concepts of Chemistry', hi: 'रसायन विज्ञान की कुछ मूल अवधारणाएँ', pa: 'ਰਸਾਇਣ ਵਿਗਿਆਨ ਦੀਆਂ ਮੁੱਢਲੀਆਂ ਧਾਰਨਾਵਾਂ' }, xp: 60, questions: [
        { question: { en: "What is Avogadro's number?", hi: "अवोगाद्रो संख्या क्या है?", pa: "ਐਵੋਗਾਡਰੋ ਨੰਬਰ ਕੀ ਹੈ?" }, options: [{en: "6.022 x 10^22", hi: "6.022 x 10^22", pa: "6.022 x 10^22"}, {en: "6.022 x 10^23", hi: "6.022 x 10^23", pa: "6.022 x 10^23"}, {en: "6.022 x 10^-23", hi: "6.022 x 10^-23", pa: "6.022 x 10^-23"}], correctAnswer: 1 },
        { question: { en: "The law of conservation of mass was given by:", hi: "द्रव्यमान संरक्षण का नियम किसके द्वारा दिया गया था:", pa: "ਪੁੰਜ ਦੀ ਸਾਂਭ-ਸੰਭਾਲ ਦਾ ਨਿਯਮ ਕਿਸ ਦੁਆਰਾ ਦਿੱਤਾ ਗਿਆ ਸੀ:" }, options: [{en: "Dalton", hi: "डाल्टन", pa: "ਡਾਲਟਨ"}, {en: "Proust", hi: "प्राउस्ट", pa: "ਪ੍ਰਾਉਸਟ"}, {en: "Lavoisier", hi: "लेवोज़ियर", pa: "ਲੈਵੋਜ਼ੀਅਰ"}], correctAnswer: 2 },
        { question: { en: "One mole of any substance contains how many particles?", hi: "किसी भी पदार्थ के एक मोल में कितने कण होते हैं?", pa: "ਕਿਸੇ ਵੀ ਪਦਾਰਥ ਦੇ ਇੱਕ ਮੋਲ ਵਿੱਚ ਕਿੰਨੇ ਕਣ ਹੁੰਦੇ ਹਨ?" }, options: [{en: "1 million", hi: "1 मिलियन", pa: "1 ਮਿਲੀਅਨ"}, {en: "Avogadro's number", hi: "अवोगाद्रो संख्या", pa: "ਐਵੋਗਾਡਰੋ ਨੰਬਰ"}, {en: "1000", hi: "1000", pa: "1000"}], correctAnswer: 1 },
      ] },
      { id: 'chem-11-2', grade: 11, title: { en: 'Structure of Atom', hi: 'परमाणु की संरचना', pa: 'ਪ੍ਰਮਾਣੂ ਦੀ ਬਣਤਰ' }, xp: 60, questions: [
        { question: { en: "Who discovered the electron?", hi: "इलेक्ट्रॉन की खोज किसने की?", pa: "ਇਲੈਕਟ੍ਰੋਨ ਦੀ ਖੋਜ ਕਿਸਨੇ ਕੀਤੀ?" }, options: [{en: "Rutherford", hi: "रदरफोर्ड", pa: "ਰਦਰਫੋਰਡ"}, {en: "J.J. Thomson", hi: "जे.जे. थॉमसन", pa: "ਜੇ.ਜੇ. ਥਾਮਸਨ"}, {en: "Chadwick", hi: "चैडविक", pa: "ਚੈਡਵਿਕ"}], correctAnswer: 1 },
        { question: { en: "The number of protons in the nucleus of an atom is called its:", hi: "एक परमाणु के नाभिक में प्रोटॉन की संख्या कहलाती है:", pa: "ਇੱਕ ਪ੍ਰਮਾਣੂ ਦੇ ਨਿਊਕਲੀਅਸ ਵਿੱਚ ਪ੍ਰੋਟੋਨਾਂ ਦੀ ਗਿਣਤੀ ਨੂੰ ਕੀ ਕਿਹਾ ਜਾਂਦਾ ਹੈ:" }, options: [{en: "Mass number", hi: "द्रव्यमान संख्या", pa: "ਪੁੰਜ ਨੰਬਰ"}, {en: "Atomic number", hi: "परमाणु क्रमांक", pa: "ਪ੍ਰਮਾਣੂ ਨੰਬਰ"}, {en: "Valency", hi: "संयोजकता", pa: "ਵੈਲੈਂਸੀ"}], correctAnswer: 1 },
        { question: { en: "The 'plum pudding' model of the atom was proposed by:", hi: "परमाणु का 'प्लम पुडिंग' मॉडल किसके द्वारा प्रस्तावित किया गया था:", pa: "ਪ੍ਰਮਾਣੂ ਦਾ 'ਪਲਮ ਪੁਡਿੰਗ' ਮਾਡਲ ਕਿਸ ਦੁਆਰਾ ਪ੍ਰਸਤਾਵਿਤ ਕੀਤਾ ਗਿਆ ਸੀ:" }, options: [{en: "Dalton", hi: "डाल्टन", pa: "ਡਾਲਟਨ"}, {en: "Rutherford", hi: "रदरफोर्ड", pa: "ਰਦਰਫੋਰਡ"}, {en: "Thomson", hi: "थॉमसन", pa: "ਥਾਮਸਨ"}], correctAnswer: 2 },
      ] },
    { id: 'chem-12-1', grade: 12, title: { en: 'Solutions', hi: 'विलयन', pa: 'ਘੋਲ' }, xp: 60, questions: [
        { question: { en: "A homogeneous mixture of two or more substances is called a:", hi: "दो या दो से अधिक पदार्थों का समांगी मिश्रण कहलाता है:", pa: "ਦੋ ਜਾਂ ਦੋ ਤੋਂ ਵੱਧ ਪਦਾਰਥਾਂ ਦੇ ਇੱਕੋ ਜਿਹੇ ਮਿਸ਼ਰਣ ਨੂੰ ਕੀ ਕਿਹਾ ਜਾਂਦਾ ਹੈ:" }, options: [{en: "Suspension", hi: "निलंबन", pa: "ਸਸਪੈਂਸ਼ਨ"}, {en: "Solution", hi: "विलयन", pa: "ਘੋਲ"}, {en: "Compound", hi: "यौगिक", pa: "ਯੋਗਿਕ"}], correctAnswer: 1 },
        { question: { en: "The component present in the largest quantity in a solution is called the:", hi: "एक विलयन में सबसे बड़ी मात्रा में मौजूद घटक कहलाता है:", pa: "ਇੱਕ ਘੋਲ ਵਿੱਚ ਸਭ ਤੋਂ ਵੱਡੀ ਮਾਤਰਾ ਵਿੱਚ ਮੌਜੂਦ ਹਿੱਸੇ ਨੂੰ ਕੀ ਕਿਹਾ ਜਾਂਦਾ ਹੈ:" }, options: [{en: "Solute", hi: "विलेय", pa: "ਘੁਲਣਸ਼ੀਲ"}, {en: "Solvent", hi: "विलायक", pa: "ਘੋਲਕ"}, {en: "Mixture", hi: "मिश्रण", pa: "ਮਿਸ਼ਰਣ"}], correctAnswer: 1 },
        { question: { en: "Molarity is defined as the number of moles of solute per:", hi: "मोलरता को विलेय के मोलों की संख्या प्रति:", pa: "ਮੋਲੈਰਿਟੀ ਨੂੰ ਘੁਲਣਸ਼ੀਲ ਦੇ ਮੋਲ ਦੀ ਗਿਣਤੀ ਪ੍ਰਤੀ:" }, options: [{en: "Kilogram of solvent", hi: "किलोग्राम विलायक", pa: "ਕਿਲੋਗ੍ਰਾਮ ਘੋਲਕ"}, {en: "Liter of solution", hi: "लीटर विलयन", pa: "ਲੀਟਰ ਘੋਲ"}, {en: "Liter of solvent", hi: "लीटर विलायक", pa: "ਲੀਟਰ ਘੋਲਕ"}], correctAnswer: 1 },
    ] },
     { id: 'chem-12-2', grade: 12, title: { en: 'Electrochemistry', hi: 'वैद्युतरसायन', pa: 'ਇਲੈਕਟ੍ਰੋਕੈਮਿਸਟਰੀ' }, xp: 60, questions: [
        { question: { en: "The process of decomposition of an electrolyte by passing electricity is called:", hi: "विद्युत प्रवाहित करके किसी विद्युत अपघट्य के अपघटन की प्रक्रिया कहलाती है:", pa: "ਬਿਜਲੀ ਪਾਸ ਕਰਕੇ ਇੱਕ ਇਲੈਕਟ੍ਰੋਲਾਈਟ ਦੇ ਸੜਨ ਦੀ ਪ੍ਰਕਿਰਿਆ ਨੂੰ ਕੀ ਕਿਹਾ ਜਾਂਦਾ ਹੈ:" }, options: [{en: "Electrolysis", hi: "विद्युतपघटन", pa: "ਇਲੈਕਟ੍ਰੋਲਾਈਸਿਸ"}, {en: "Oxidation", hi: "ऑक्सीकरण", pa: "ਆਕਸੀਕਰਨ"}, {en: "Reduction", hi: "अपचयन", pa: "ਕਮੀ"}], correctAnswer: 0 },
        { question: { en: "A device that converts chemical energy into electrical energy is a:", hi: "एक उपकरण जो रासायनिक ऊर्जा को विद्युत ऊर्जा में परिवर्तित करता है, वह है:", pa: "ਇੱਕ ਯੰਤਰ ਜੋ ਰਸਾਇਣਕ ਊਰਜਾ ਨੂੰ ਬਿਜਲਈ ਊਰਜਾ ਵਿੱਚ ਬਦਲਦਾ ਹੈ, ਉਹ ਹੈ:" }, options: [{en: "Motor", hi: "मोटर", pa: "ਮੋਟਰ"}, {en: "Galvanic cell", hi: "गैल्वेनिक सेल", pa: "ਗੈਲਵੈਨਿਕ ਸੈੱਲ"}, {en: "Electrolytic cell", hi: "विद्युत अपघटनी सेल", pa: "ਇਲੈਕਟ੍ਰੋਲਾਈਟਿਕ ਸੈੱਲ"}], correctAnswer: 1 },
        { question: { en: "The Nernst equation relates the cell potential to:", hi: "नर्न्स्ट समीकरण सेल विभव को किससे संबंधित करता है:", pa: "ਨਰਨਸਟ ਸਮੀਕਰਨ ਸੈੱਲ ਦੀ ਸੰਭਾਵਨਾ ਨੂੰ ਕਿਸ ਨਾਲ ਸਬੰਧਤ ਕਰਦਾ ਹੈ:" }, options: [{en: "Temperature", hi: "तापमान", pa: "ਤਾਪਮਾਨ"}, {en: "Concentration", hi: "सांद्रता", pa: "ਇਕਾਗਰਤਾ"}, {en: "Both A and B", hi: "A और B दोनों", pa: "A ਅਤੇ B ਦੋਵੇਂ"}], correctAnswer: 2 },
    ] },
    { id: 'chem-12-3', grade: 12, title: { en: 'Chemical Kinetics', hi: 'रासायनिक बलगतिकी', pa: 'ਰਸਾਇਣਕ ਗਤੀ ਵਿਗਿਆਨ' }, xp: 70, questions: [
        { question: { en: "The rate of a reaction is affected by:", hi: "एक अभिक्रिया की दर किससे प्रभावित होती है:", pa: "ਇੱਕ ਪ੍ਰਤੀਕ੍ਰਿਆ ਦੀ ਦਰ ਕਿਸ ਦੁਆਰਾ ਪ੍ਰਭਾਵਿਤ ਹੁੰਦੀ ਹੈ:" }, options: [{en: "Temperature", hi: "तापमान", pa: "ਤਾਪਮਾਨ"}, {en: "Concentration", hi: "सांद्रता", pa: "ਇਕਾਗਰਤਾ"}, {en: "All of the above", hi: "उपरोक्त सभी", pa: "ਉਪਰੋਕਤ ਸਾਰੇ"}], correctAnswer: 2 },
        { question: { en: "The unit of rate of reaction is:", hi: "अभिक्रिया की दर की इकाई है:", pa: "ਪ੍ਰਤੀਕ੍ਰਿਆ ਦੀ ਦਰ ਦੀ ਇਕਾਈ ਹੈ:" }, options: [{en: "mol L⁻¹ s⁻¹", hi: "मोल L⁻¹ s⁻¹", pa: "ਮੋਲ L⁻¹ s⁻¹"}, {en: "L mol⁻¹ s⁻¹", hi: "L मोल⁻¹ s⁻¹", pa: "L ਮੋਲ⁻¹ s⁻¹"}, {en: "s⁻¹", hi: "s⁻¹", pa: "s⁻¹"}], correctAnswer: 0 },
        { question: { en: "A catalyst increases the rate of a reaction by:", hi: "एक उत्प्रेरक अभिक्रिया की दर को बढ़ाता है:", pa: "ਇੱਕ ਉਤਪ੍ਰੇਰਕ ਇੱਕ ਪ੍ਰਤੀਕ੍ਰਿਆ ਦੀ ਦਰ ਨੂੰ ਵਧਾਉਂਦਾ ਹੈ:" }, options: [{en: "Increasing activation energy", hi: "सक्रियण ऊर्जा को बढ़ाकर", pa: "ਸਰਗਰਮੀ ਊਰਜਾ ਨੂੰ ਵਧਾ ਕੇ"}, {en: "Decreasing activation energy", hi: "सक्रियण ऊर्जा को घटाकर", pa: "ਸਰਗਰਮੀ ਊਰਜਾ ਨੂੰ ਘਟਾ ਕੇ"}, {en: "Increasing temperature", hi: "तापमान बढ़ाकर", pa: "ਤਾਪਮਾਨ ਵਧਾ ਕੇ"}], correctAnswer: 1 },
    ] },
    { id: 'chem-12-4', grade: 12, title: { en: 'd and f Block Elements', hi: 'd और f ब्लॉक के तत्व', pa: 'd ਅਤੇ f ਬਲਾਕ ਤੱਤ' }, xp: 70, questions: [
        { question: { en: "The elements of d-block are also known as:", hi: "d-ब्लॉक के तत्वों को इस रूप में भी जाना जाता है:", pa: "d-ਬਲਾਕ ਦੇ ਤੱਤਾਂ ਨੂੰ ਇਸ ਰੂਪ ਵਿੱਚ ਵੀ ਜਾਣਿਆ ਜਾਂਦਾ ਹੈ:" }, options: [{en: "Alkali metals", hi: "क्षार धातु", pa: "ਖਾਰੀ ਧਾਤਾਂ"}, {en: "Transition metals", hi: "संक्रमण धातु", pa: "ਤਬਦੀਲੀ ਧਾਤਾਂ"}, {en: "Noble gases", hi: "उत्कृष्ट गैसें", pa: "ਨੇਕ ਗੈਸਾਂ"}], correctAnswer: 1 },
        { question: { en: "Which of the following is a characteristic of transition metals?", hi: "निम्नलिखित में से कौन सा संक्रमण धातुओं का एक लक्षण है?", pa: "ਹੇਠ ਲਿਖਿਆਂ ਵਿੱਚੋਂ ਕਿਹੜਾ ਤਬਦੀਲੀ ਧਾਤਾਂ ਦਾ ਇੱਕ ਗੁਣ ਹੈ?" }, options: [{en: "Form colored ions", hi: "रंगीन आयन बनाते हैं", pa: "ਰੰਗੀਨ ਆਇਨ ਬਣਾਉਂਦੇ ਹਨ"}, {en: "Show variable oxidation states", hi: "परिवर्तनीय ऑक्सीकरण अवस्थाएं दिखाते हैं", pa: "ਪਰਿਵਰਤਨਸ਼ੀਲ ਆਕਸੀਕਰਨ ਅਵਸਥਾਵਾਂ ਦਿਖਾਉਂਦੇ ਹਨ"}, {en: "All of the above", hi: "उपरोक्त सभी", pa: "ਉਪਰੋਕਤ ਸਾਰੇ"}], correctAnswer: 2 },
        { question: { en: "The f-block elements are also called:", hi: "f-ब्लॉक के तत्वों को यह भी कहा जाता है:", pa: "f-ਬਲਾਕ ਤੱਤਾਂ ਨੂੰ ਇਹ ਵੀ ਕਿਹਾ ਜਾਂਦਾ ਹੈ:" }, options: [{en: "Inner transition elements", hi: "आंतरिक संक्रमण तत्व", pa: "ਅੰਦਰੂਨੀ ਤਬਦੀਲੀ ਤੱਤ"}, {en: "Representative elements", hi: "प्रतिनिधि तत्व", pa: "ਪ੍ਰਤੀਨਿਧੀ ਤੱਤ"}, {en: "Halogens", hi: "हैलोजन", pa: "ਹੈਲੋਜਨ"}], correctAnswer: 0 },
    ] },
    { id: 'chem-12-5', grade: 12, title: { en: 'Biomolecules', hi: 'जैव-अणु', pa: 'ਜੀਵ-ਅਣੂ' }, xp: 70, questions: [
      { question: { en: "Which of the following is a monosaccharide?", hi: "निम्नलिखित में से कौन सा एक मोनोसैकराइड है?", pa: "ਹੇਠ ਲਿਖਿਆਂ ਵਿੱਚੋਂ ਕਿਹੜਾ ਇੱਕ ਮੋਨੋਸੈਕਰਾਈਡ ਹੈ?" }, options: [{en: "Sucrose", hi: "सुक्रोज", pa: "ਸੂਕਰੋਜ਼"}, {en: "Glucose", hi: "ग्लूकोज", pa: "ਗਲੂਕੋਜ਼"}, {en: "Cellulose", hi: "सेल्यूलोज", pa: "ਸੈਲੂਲੋਜ਼"}], correctAnswer: 1 },
      { question: { en: "Proteins are polymers of:", hi: "प्रोटीन किसके बहुलक हैं:", pa: "ਪ੍ਰੋਟੀਨ ਕਿਸਦੇ ਪੋਲੀਮਰ ਹਨ:" }, options: [{en: "Glucose", hi: "ग्लूकोज", pa: "ਗਲੂਕੋਜ਼"}, {en: "Amino acids", hi: "अमीनो एसिड", pa: "ਅਮੀਨੋ ਐਸਿਡ"}, {en: "Fatty acids", hi: "वसा अम्ल", pa: "ਫੈਟੀ ਐਸਿਡ"}], correctAnswer: 1 },
      { question: { en: "Which vitamin deficiency causes scurvy?", hi: "किस विटामिन की कमी से स्कर्वी होता है?", pa: "ਕਿਹੜੇ ਵਿਟਾਮਿਨ ਦੀ ਕਮੀ ਨਾਲ ਸਕਰਵੀ ਹੁੰਦੀ ਹੈ?" }, options: [{en: "Vitamin A", hi: "विटामिन ए", pa: "ਵਿਟਾਮਿਨ ਏ"}, {en: "Vitamin C", hi: "विटामिन सी", pa: "ਵਿਟਾਮਿਨ ਸੀ"}, {en: "Vitamin D", hi: "विटामिन डी", pa: "ਵਿਟਾਮਿਨ ਡੀ"}], correctAnswer: 1 },
    ] },
  ],
  biology: [
      { id: 'bio-11-1', grade: 11, title: { en: 'The Living World', hi: 'जीव जगत', pa: 'ਜੀਵਤ ਸੰਸਾਰ' }, xp: 50, questions: [
        { question: { en: "Who is known as the father of taxonomy?", hi: "वर्गीकरण का जनक किसे कहा जाता है?", pa: "ਟੈਕਸੋਨੋਮੀ ਦਾ ਪਿਤਾਮਾ ਕਿਸਨੂੰ ਕਿਹਾ ਜਾਂਦਾ ਹੈ?" }, options: [{en: "Aristotle", hi: "अरस्तू", pa: "ਅਰਸਤੂ"}, {en: "Linnaeus", hi: "लिनिअस", pa: "ਲਿਨੀਅਸ"}, {en: "Darwin", hi: "डार्विन", pa: "ਡਾਰਵਿਨ"}], correctAnswer: 1 },
        { question: { en: "What is the basic unit of classification?", hi: "वर्गीकरण की मूल इकाई क्या है?", pa: "ਵਰਗੀਕਰਨ ਦੀ ਮੁੱਢਲੀ ਇਕਾਈ ਕੀ ਹੈ?" }, options: [{en: "Kingdom", hi: "जगत", pa: "ਕਿੰਗਡਮ"}, {en: "Genus", hi: "वंश", pa: "ਜੀਨਸ"}, {en: "Species", hi: "जाति", pa: "ਸਪੀਸੀਜ਼"}], correctAnswer: 2 },
        { question: { en: "Binomial nomenclature was introduced by:", hi: "द्विपद नामकरण किसके द्वारा प्रस्तुत किया गया था:", pa: "ਦੋ-ਨਾਮੀ ਨਾਮਕਰਨ ਕਿਸ ਦੁਆਰਾ ਪੇਸ਼ ਕੀਤਾ ਗਿਆ ਸੀ:" }, options: [{en: "Charles Darwin", hi: "चार्ल्स डार्विन", pa: "ਚਾਰਲਸ ਡਾਰਵਿਨ"}, {en: "Carolus Linnaeus", hi: "कैरोलस लिनिअस", pa: "ਕੈਰੋਲਸ ਲਿਨੀਅਸ"}, {en: "Robert Hooke", hi: "रॉबर्ट हुक", pa: "ਰਾਬਰਟ ਹੁੱਕ"}], correctAnswer: 1 },
      ] },
      { id: 'bio-11-2', grade: 11, title: { en: 'Cell: The Unit of Life', hi: 'कोशिका: जीवन की इकाई', pa: 'ਸੈੱਲ: ਜੀਵਨ ਦੀ ਇਕਾਈ' }, xp: 60, questions: [
        { question: { en: "The 'powerhouse' of the cell is the:", hi: "कोशिका का 'ऊर्जा घर' है:", pa: "ਸੈੱਲ ਦਾ 'ਪਾਵਰਹਾਊਸ' ਹੈ:" }, options: [{en: "Nucleus", hi: "केन्द्रक", pa: "ਨਿਊਕਲੀਅਸ"}, {en: "Mitochondrion", hi: "माइटोकॉन्ड्रियन", pa: "ਮਾਈਟੋਕਾਂਡਰੀਆ"}, {en: "Golgi apparatus", hi: "गॉल्जी उपकरण", pa: "ਗੋਲਗੀ ਉਪਕਰਣ"}], correctAnswer: 1 },
        { question: { en: "Which organelle is responsible for protein synthesis?", hi: "कौन सा कोशिकांग प्रोटीन संश्लेषण के लिए जिम्मेदार है?", pa: "ਕਿਹੜਾ ਔਰਗਨੇਲ ਪ੍ਰੋਟੀਨ ਸੰਸਲੇਸ਼ਣ ਲਈ ਜ਼ਿੰਮੇਵਾਰ ਹੈ?" }, options: [{en: "Lysosome", hi: "लाइसोसोम", pa: "ਲਾਈਸੋਸੋਮ"}, {en: "Ribosome", hi: "राइबोसोम", pa: "ਰਾਈਬੋਸੋਮ"}, {en: "Vacuole", hi: "रिक्तिका", pa: "ਵੈਕਿਊਲ"}], correctAnswer: 1 },
        { question: { en: "The control center of the cell is the:", hi: "कोशिका का नियंत्रण केंद्र है:", pa: "ਸੈੱਲ ਦਾ ਨਿਯੰਤਰਣ ਕੇਂਦਰ ਹੈ:" }, options: [{en: "Nucleus", hi: "केन्द्रक", pa: "ਨਿਊਕਲੀਅਸ"}, {en: "Cytoplasm", hi: "कोशिकाद्रव्य", pa: "ਸਾਈਟੋਪਲਾਜ਼ਮ"}, {en: "Cell membrane", hi: "कोशिका झिल्ली", pa: "ਸੈੱਲ ਝਿੱਲੀ"}], correctAnswer: 0 },
      ] },
      { id: 'bio-12-1', grade: 12, title: { en: 'Reproduction in Organisms', hi: 'जीवों में जनन', pa: 'ਜੀਵਾਂ ਵਿੱਚ ਪ੍ਰਜਨਨ' }, xp: 50, questions: [
        { question: { en: "Which is a mode of asexual reproduction?", hi: "अलैंगिक जनन की एक विधि कौन सी है?", pa: "ਅਲੈਂਗਿਕ ਪ੍ਰਜਨਨ ਦਾ ਇੱਕ ਢੰਗ ਕਿਹੜਾ ਹੈ?" }, options: [{en: "Budding", hi: "मुकुलन", pa: "ਬਡਿੰਗ"}, {en: "Fertilization", hi: "निषेचन", pa: "ਗਰਭਧਾਰਨ"}, {en: "Pollination", hi: "परागण", pa: "ਪਰਾਗਣ"}], correctAnswer: 0 },
        { question: { en: "Sexual reproduction involves the fusion of:", hi: "लैंगिक जनन में किसका संलयन होता है:", pa: "ਲੈਂਗਿਕ ਪ੍ਰਜਨਨ ਵਿੱਚ ਕਿਸਦਾ ਸੰਯੋਜਨ ਹੁੰਦਾ ਹੈ:" }, options: [{en: "Spores", hi: "बीजाणु", pa: "ਸਪੋਰਸ"}, {en: "Gametes", hi: "युग्मक", pa: "ਗੈਮੇਟਸ"}, {en: "Zoospores", hi: "चलबीजाणु", pa: "ਜ਼ੂਸਪੋਰਸ"}], correctAnswer: 1 },
        { question: { en: "An example of vegetative propagation by leaves is seen in:", hi: "पत्तियों द्वारा कायिक प्रवर्धन का एक उदाहरण देखा जाता है:", pa: "ਪੱਤਿਆਂ ਦੁਆਰਾ ਬਨਸਪਤੀ ਪ੍ਰਸਾਰ ਦੀ ਇੱਕ ਉਦਾਹਰਣ ਵੇਖੀ ਜਾਂਦੀ ਹੈ:" }, options: [{en: "Rose", hi: "गुलाब", pa: "ਗੁਲਾਬ"}, {en: "Bryophyllum", hi: "ब्रायोफिलम", pa: "ਬ੍ਰਾਇਓਫਿਲਮ"}, {en: "Potato", hi: "आलू", pa: "ਆਲੂ"}], correctAnswer: 1 },
      ] },
      { id: 'bio-12-2', grade: 12, title: { en: 'Human Reproduction', hi: 'मानव जनन', pa: 'ਮਨੁੱਖੀ ਪ੍ਰਜਨਨ' }, xp: 60, questions: [
        { question: { en: "Fertilization in humans occurs in the:", hi: "मनुष्यों में निषेचन कहाँ होता है:", pa: "ਮਨੁੱਖਾਂ ਵਿੱਚ ਗਰਭਧਾਰਨ ਕਿੱਥੇ ਹੁੰਦਾ ਹੈ:" }, options: [{en: "Ovary", hi: "अंडाशय", pa: "ਅੰਡਾਸ਼ਯ"}, {en: "Uterus", hi: "गर्भाशय", pa: "ਬੱਚੇਦਾਨੀ"}, {en: "Fallopian tube", hi: "डिंबवाहिनी", pa: "ਫੈਲੋਪੀਅਨ ਟਿਊਬ"}], correctAnswer: 2 },
        { question: { en: "The male gamete is called:", hi: "नर युग्मक को कहा जाता है:", pa: "ਨਰ ਗੈਮੇਟ ਨੂੰ ਕੀ ਕਿਹਾ ਜਾਂਦਾ ਹੈ:" }, options: [{en: "Ovum", hi: "अंडाणु", pa: "ਅੰਡਾਣੂ"}, {en: "Sperm", hi: "शुक्राणु", pa: "ਸ਼ੁਕਰਾਣੂ"}, {en: "Zygote", hi: "युग्मनज", pa: "ਜ਼ਾਈਗੋਟ"}], correctAnswer: 1 },
        { question: { en: "The primary male reproductive organ is:", hi: "प्राथमिक पुरुष प्रजनन अंग है:", pa: "ਪ੍ਰਾਇਮਰੀ ਨਰ ਪ੍ਰਜਨਨ ਅੰਗ ਹੈ:" }, options: [{en: "Testis", hi: "वृषण", pa: "ਅੰਡਕੋਸ਼"}, {en: "Penis", hi: "शिश्न", pa: "ਲਿੰਗ"}, {en: "Scrotum", hi: "वृषणकोष", pa: "ਅੰਡਕੋਸ਼"}], correctAnswer: 0 },
      ] },
       { id: 'bio-12-3', grade: 12, title: { en: 'Principles of Inheritance', hi: 'वंशागति के सिद्धांत', pa: 'ਵਿਰਾਸਤ ਦੇ ਸਿਧਾਂਤ' }, xp: 70, questions: [
        { question: { en: "Who is known as the father of genetics?", hi: "आनुवंशिकी का जनक किसे कहा जाता है?", pa: "ਜੈਨੇਟਿਕਸ ਦਾ ਪਿਤਾਮਾ ਕਿਸਨੂੰ ਕਿਹਾ ਜਾਂਦਾ ਹੈ?" }, options: [{en: "Darwin", hi: "डार्विन", pa: "ਡਾਰਵਿਨ"}, {en: "Mendel", hi: "मेंडल", pa: "ਮੈਂਡਲ"}, {en: "Morgan", hi: "मॉर्गन", pa: "ਮੋਰਗਨ"}], correctAnswer: 1 },
        { question: { en: "An alternate form of a gene is called an:", hi: "एक जीन के वैकल्पिक रूप को कहा जाता है:", pa: "ਇੱਕ ਜੀਨ ਦੇ ਵਿਕਲਪਿਕ ਰੂਪ ਨੂੰ ਕੀ ਕਿਹਾ ਜਾਂਦਾ ਹੈ:" }, options: [{en: "Allele", hi: "युग्मविकल्पी", pa: "ਐਲੀਲ"}, {en: "Locus", hi: "लोकस", pa: "ਲੋਕਸ"}, {en: "Phenotype", hi: "लक्षणप्ररूप", pa: "ਫੀਨੋਟਾਈਪ"}], correctAnswer: 0 },
        { question: { en: "The genetic makeup of an organism is its:", hi: "एक जीव की आनुवंशिक संरचना है:", pa: "ਇੱਕ ਜੀਵ ਦੀ ਜੈਨੇਟਿਕ ਬਣਤਰ ਹੈ:" }, options: [{en: "Phenotype", hi: "लक्षणप्ररूप", pa: "ਫੀਨੋਟਾਈਪ"}, {en: "Genotype", hi: "जीनप्ररूप", pa: "ਜੀਨੋਟਾਈਪ"}, {en: "Genome", hi: "जीनोम", pa: "ਜੀਨੋਮ"}], correctAnswer: 1 },
      ] },
       { id: 'bio-12-4', grade: 12, title: { en: 'Molecular Basis of Inheritance', hi: 'वंशागति का आणविक आधार', pa: 'ਵਿਰਾਸਤ ਦਾ ਅਣੂ ਅਧਾਰ' }, xp: 80, questions: [
        { question: { en: "DNA is a polymer of:", hi: "डीएनए किसका बहुलक है:", pa: "ਡੀਐਨਏ ਕਿਸਦਾ ਇੱਕ ਪੋਲੀਮਰ ਹੈ:" }, options: [{en: "Amino acids", hi: "अमीनो एसिड", pa: "ਅਮੀਨੋ ਐਸਿਡ"}, {en: "Nucleotides", hi: "न्यूक्लियोटाइड", pa: "ਨਿਊਕਲੀਓਟਾਈਡ"}, {en: "Monosaccharides", hi: "मोनोसैकराइड", pa: "ਮੋਨੋਸੈਕਰਾਈਡ"}], correctAnswer: 1 },
        { question: { en: "The structure of DNA was given by:", hi: "डीएनए की संरचना किसके द्वारा दी गई थी:", pa: "ਡੀਐਨਏ ਦੀ ਬਣਤਰ ਕਿਸ ਦੁਆਰਾ ਦਿੱਤੀ ਗਈ ਸੀ:" }, options: [{en: "Watson and Crick", hi: "वॉटसन और क्रिक", pa: "ਵਾਟਸਨ ਅਤੇ ਕ੍ਰਿਕ"}, {en: "Khorana", hi: "खुराना", pa: "ਖੁਰਾਣਾ"}, {en: "Nirenberg", hi: "निरेनबर्ग", pa: "ਨਿਰੇਨਬਰਗ"}], correctAnswer: 0 },
        { question: { en: "The process of forming mRNA from DNA is called:", hi: "डीएनए से mRNA बनाने की प्रक्रिया को कहा जाता है:", pa: "ਡੀਐਨਏ ਤੋਂ mRNA ਬਣਾਉਣ ਦੀ ਪ੍ਰਕਿਰਿਆ ਨੂੰ ਕੀ ਕਿਹਾ ਜਾਂਦਾ ਹੈ:" }, options: [{en: "Translation", hi: "अनुवाद", pa: "ਅਨੁਵਾਦ"}, {en: "Replication", hi: "प्रतिकृति", pa: "ਪ੍ਰਤੀਕ੍ਰਿਤੀ"}, {en: "Transcription", hi: "अनुलेखन", pa: "ਟ੍ਰਾਂਸਕ੍ਰਿਪਸ਼ਨ"}], correctAnswer: 2 },
      ] },
      { id: 'bio-12-5', grade: 12, title: { en: 'Biotechnology', hi: 'जैव प्रौद्योगिकी', pa: 'ਬਾਇਓਟੈਕਨਾਲੌਜੀ' }, xp: 70, questions: [
        { question: { en: "Recombinant DNA technology involves:", hi: "पुनर्योगज डीएनए प्रौद्योगिकी में शामिल है:", pa: "ਰੀਕੌਂਬੀਨੈਂਟ ਡੀਐਨਏ ਟੈਕਨਾਲੋਜੀ ਵਿੱਚ ਸ਼ਾਮਲ ਹੈ:" }, options: [{en: "Gene cloning", hi: "जीन क्लोनिंग", pa: "ਜੀਨ ਕਲੋਨਿੰਗ"}, {en: "DNA sequencing", hi: "डीएनए अनुक्रमण", pa: "ਡੀਐਨਏ ਕ੍ਰਮ"}, {en: "Protein synthesis", hi: "प्रोटीन संश्लेषण", pa: "ਪ੍ਰੋਟੀਨ ਸੰਸਲੇਸ਼ਣ"}], correctAnswer: 0 },
        { question: { en: "Plasmids are commonly used as:", hi: "प्लास्मिड का उपयोग आमतौर पर किसके रूप में किया जाता है:", pa: "ਪਲਾਜ਼ਮਿਡ ਆਮ ਤੌਰ 'ਤੇ ਕਿਸ ਵਜੋਂ ਵਰਤੇ ਜਾਂਦੇ ਹਨ:" }, options: [{en: "Enzymes", hi: "एंजाइम", pa: "ਐਨਜ਼ਾਈਮ"}, {en: "Vectors", hi: "वैक्टर", pa: "ਵੈਕਟਰ"}, {en: "Hosts", hi: "मेजबान", pa: "ਮੇਜ਼ਬਾਨ"}], correctAnswer: 1 },
        { question: { en: "PCR stands for:", hi: "पीसीआर का मतलब है:", pa: "ਪੀਸੀਆਰ ਦਾ ਪੂਰਾ ਨਾਮ ਕੀ ਹੈ:" }, options: [{en: "Polymerase Chain Reaction", hi: "पोलीमरेज़ चेन रिएक्शन", pa: "ਪੋਲੀਮੇਰੇਜ਼ ਚੇਨ ਰਿਐਕਸ਼ਨ"}, {en: "Protein Chain Reaction", hi: "प्रोटीन चेन रिएक्शन", pa: "ਪ੍ਰੋਟੀਨ ਚੇਨ ਰਿਐਕਸ਼ਨ"}, {en: "Primary Cell Reaction", hi: "प्राथमिक सेल रिएक्शन", pa: "ਪ੍ਰਾਇਮਰੀ ਸੈੱਲ ਰਿਐਕਸ਼ਨ"}], correctAnswer: 0 },
      ] },
  ],
  computer_science: [
      { id: 'cs-11-1', grade: 11, title: { en: 'Number Systems', hi: 'संख्या प्रणाली', pa: 'ਨੰਬਰ ਸਿਸਟਮ' }, xp: 50, questions: [
        { question: { en: "What is the binary equivalent of the decimal number 10?", hi: "दशमलव संख्या 10 का बाइनरी समतुल्य क्या है?", pa: "ਡੈਸੀਮਲ ਨੰਬਰ 10 ਦੇ ਬਰਾਬਰ ਬਾਈਨਰੀ ਕੀ ਹੈ?" }, options: [{en: "1010", hi: "1010", pa: "1010"}, {en: "1100", hi: "1100", pa: "1100"}, {en: "1001", hi: "1001", pa: "1001"}], correctAnswer: 0 },
        { question: { en: "Which number system has a base of 16?", hi: "किस संख्या प्रणाली का आधार 16 है?", pa: "ਕਿਹੜੇ ਨੰਬਰ ਸਿਸਟਮ ਦਾ ਬੇਸ 16 ਹੈ?" }, options: [{en: "Binary", hi: "बाइनरी", pa: "ਬਾਈਨਰੀ"}, {en: "Hexadecimal", hi: "हेक्साडेसिमल", pa: "ਹੈਕਸਾਡੈਸੀਮਲ"}, {en: "Decimal", hi: "डेसीमल", pa: "ਡੈਸੀਮਲ"}], correctAnswer: 1 },
        { question: { en: "DBMS stands for:", hi: "DBMS का मतलब है:", pa: "DBMS ਦਾ ਪੂਰਾ ਨਾਮ ਕੀ ਹੈ:" }, options: [{en: "Database Management System", hi: "डेटाबेस मैनेजमेंट सिस्टम", pa: "ਡਾਟਾਬੇਸ ਮੈਨੇਜਮੈਂਟ ਸਿਸਟਮ"}, {en: "Data Backup Management System", hi: "डेटा बैकअप मैनेजमेंट सिस्टम", pa: "ਡੇਟਾ ਬੈਕਅੱਪ ਮੈਨੇਜਮੈਂਟ ਸਿਸਟਮ"}, {en: "Digital Base Mapping System", hi: "डिजिटल बेस मैपिंग सिस्टम", pa: "ਡਿਜੀਟਲ ਬੇਸ ਮੈਪਿੰਗ ਸਿਸਟਮ"}], correctAnswer: 0 },
      ] },
       { id: 'cs-11-2', grade: 11, title: { en: 'Python Programming Basics', hi: 'पाइथन प्रोग्रामिंग की मूल बातें', pa: 'ਪਾਈਥਨ ਪ੍ਰੋਗਰਾਮਿੰਗ ਦੀਆਂ ਮੂਲ ਗੱਲਾਂ' }, xp: 70, questions: [
        { question: { en: "What is used to define a block of code in Python?", hi: "पाइथन में कोड के एक ब्लॉक को परिभाषित करने के लिए क्या उपयोग किया जाता है?", pa: "ਪਾਈਥਨ ਵਿੱਚ ਕੋਡ ਦੇ ਇੱਕ ਬਲਾਕ ਨੂੰ ਪਰਿਭਾਸ਼ਿਤ ਕਰਨ ਲਈ ਕੀ ਵਰਤਿਆ ਜਾਂਦਾ ਹੈ?" }, options: [{en: "Curly braces {}", hi: "कर्ली ब्रेसिज़ {}", pa: "ਕਰਲੀ ਬਰੇਸਿਜ਼ {}"}, {en: "Indentation", hi: "इंडेंटेशन", pa: "ਇੰਡੈਂਟੇਸ਼ਨ"}, {en: "Quotation marks \"\"", hi: "कोटेशन मार्क्स \"\"", pa: "ਕੋਟੇਸ਼ਨ ਮਾਰਕਸ \"\""}], correctAnswer: 1 },
        { question: { en: "Which keyword is used to create a function in Python?", hi: "पाइथन में एक फ़ंक्शन बनाने के लिए किस कीवर्ड का उपयोग किया जाता है?", pa: "ਪਾਈਥਨ ਵਿੱਚ ਇੱਕ ਫੰਕਸ਼ਨ ਬਣਾਉਣ ਲਈ ਕਿਹੜਾ ਕੀਵਰਡ ਵਰਤਿਆ ਜਾਂਦਾ ਹੈ?" }, options: [{en: "function", hi: "function", pa: "function"}, {en: "def", hi: "def", pa: "def"}, {en: "fun", hi: "fun", pa: "fun"}], correctAnswer: 1 },
        { question: { en: "How do you write a single-line comment in Python?", hi: "आप पाइथन में एक-पंक्ति टिप्पणी कैसे लिखते हैं?", pa: "ਤੁਸੀਂ ਪਾਈਥਨ ਵਿੱਚ ਇੱਕ-ਲਾਈਨ ਟਿੱਪਣੀ ਕਿਵੇਂ ਲਿਖਦੇ ਹੋ?" }, options: [{en: "// This is a comment", hi: "// यह एक टिप्पणी है", pa: "// ਇਹ ਇੱਕ ਟਿੱਪਣੀ ਹੈ"}, {en: "/* This is a comment */", hi: "/* यह एक टिप्पणी है */", pa: "/* ਇਹ ਇੱਕ ਟਿੱਪਣੀ ਹੈ */"}, {en: "# This is a comment", hi: "# यह एक टिप्पणी है", pa: "# ਇਹ ਇੱਕ ਟਿੱਪਣੀ ਹੈ"}], correctAnswer: 2 },
      ] },
      { id: 'cs-12-1', grade: 12, title: { en: 'Python Revision Tour', hi: 'पाइथन रिवीजन टूर', pa: 'ਪਾਈਥਨ ਰਿਵੀਜ਼ਨ ਟੂਰ' }, xp: 50, questions: [
        { question: { en: "Which data type would you use to store a list of items that can be changed?", hi: "आप उन आइटम्स की सूची को संग्रहीत करने के लिए किस डेटा प्रकार का उपयोग करेंगे जिन्हें बदला जा सकता है?", pa: "ਤੁਸੀਂ ਉਹਨਾਂ ਆਈਟਮਾਂ ਦੀ ਸੂਚੀ ਨੂੰ ਸਟੋਰ ਕਰਨ ਲਈ ਕਿਸ ਡਾਟਾ ਕਿਸਮ ਦੀ ਵਰਤੋਂ ਕਰੋਗੇ ਜਿਨ੍ਹਾਂ ਨੂੰ ਬਦਲਿਆ ਜਾ ਸਕਦਾ ਹੈ?" }, options: [{en: "Tuple", hi: "टपल", pa: "ਟਪਲ"}, {en: "List", hi: "लिस्ट", pa: "ਲਿਸਟ"}, {en: "String", hi: "स्ट्रिंग", pa: "ਸਟਰਿੰਗ"}], correctAnswer: 1 },
        { question: { en: "What is the output of len('Hello')?", hi: "len('Hello') का आउटपुट क्या है?", pa: "len('Hello') ਦਾ ਆਉਟਪੁੱਟ ਕੀ ਹੈ?" }, options: [{en: "4", hi: "4", pa: "4"}, {en: "5", hi: "5", pa: "5"}, {en: "6", hi: "6", pa: "6"}], correctAnswer: 1 },
        { question: { en: "Which operator checks if two values are equal?", hi: "कौन सा ऑपरेटर जांचता है कि दो मान बराबर हैं?", pa: "ਕਿਹੜਾ ਓਪਰੇਟਰ ਜਾਂਚ ਕਰਦਾ ਹੈ ਕਿ ਦੋ ਮੁੱਲ ਬਰਾਬਰ ਹਨ?" }, options: [{en: "=", hi: "=", pa: "="}, {en: "==", hi: "==", pa: "=="}, {en: "!=", hi: "!=", pa: "!="}], correctAnswer: 1 },
      ] },
      { id: 'cs-12-2', grade: 12, title: { en: 'Functions in Python', hi: 'पाइथन में फ़ंक्शंस', pa: 'ਪਾਈਥਨ ਵਿੱਚ ਫੰਕਸ਼ਨ' }, xp: 60, questions: [
        { question: { en: "What does a function's `return` statement do?", hi: "एक फ़ंक्शन का `return` स्टेटमेंट क्या करता है?", pa: "ਇੱਕ ਫੰਕਸ਼ਨ ਦਾ `return` ਸਟੇਟਮੈਂਟ ਕੀ ਕਰਦਾ ਹੈ?" }, options: [{en: "Prints a value", hi: "एक मान प्रिंट करता है", pa: "ਇੱਕ ਮੁੱਲ ਪ੍ਰਿੰਟ ਕਰਦਾ ਹੈ"}, {en: "Ends the function and sends back a value", hi: "फ़ंक्शन को समाप्त करता है और एक मान वापस भेजता है", pa: "ਫੰਕਸ਼ਨ ਨੂੰ ਖਤਮ ਕਰਦਾ ਹੈ ਅਤੇ ਇੱਕ ਮੁੱਲ ਵਾਪਸ ਭੇਜਦਾ ਹੈ"}, {en: "Starts the function", hi: "फ़ंक्शन शुरू करता है", pa: "ਫੰਕਸ਼ਨ ਸ਼ੁਰੂ ਕਰਦਾ ਹੈ"}], correctAnswer: 1 },
        { question: { en: "Arguments passed to a function are:", hi: "एक फ़ंक्शन को दिए गए तर्क हैं:", pa: "ਇੱਕ ਫੰਕਸ਼ਨ ਨੂੰ ਦਿੱਤੇ ਗਏ ਆਰਗੂਮੈਂਟ ਹਨ:" }, options: [{en: "Values received by the function", hi: "फ़ंक्शन द्वारा प्राप्त मान", pa: "ਫੰਕਸ਼ਨ ਦੁਆਰਾ ਪ੍ਰਾਪਤ ਕੀਤੇ ਮੁੱਲ"}, {en: "Variables defined inside the function", hi: "फ़ंक्शन के अंदर परिभाषित चर", pa: "ਫੰਕਸ਼ਨ ਦੇ ਅੰਦਰ ਪਰਿਭਾਸ਼ਿਤ ਵੇਰੀਏਬਲ"}, {en: "The name of the function", hi: "फ़ंक्शन का नाम", pa: "ਫੰਕਸ਼ਨ ਦਾ ਨਾਮ"}], correctAnswer: 0 },
        { question: { en: "A function without a `return` statement returns:", hi: "`return` स्टेटमेंट के बिना एक फ़ंक्शन वापस आता है:", pa: "`return` ਸਟੇਟਮੈਂਟ ਤੋਂ ਬਿਨਾਂ ਇੱਕ ਫੰਕਸ਼ਨ ਵਾਪਸ ਆਉਂਦਾ ਹੈ:" }, options: [{en: "0", hi: "0", pa: "0"}, {en: "An error", hi: "एक त्रुटि", pa: "ਇੱਕ ਗਲਤੀ"}, {en: "None", hi: "कुछ नहीं", pa: "ਕੋਈ ਨਹੀਂ"}], correctAnswer: 2 },
      ] },
      { id: 'cs-12-3', grade: 12, title: { en: 'File Handling', hi: 'फ़ाइल हैंडलिंग', pa: 'ਫਾਈਲ ਹੈਂਡਲਿੰਗ' }, xp: 60, questions: [
        { question: { en: "Which mode is used to open a file for writing, which overwrites the file?", hi: "फ़ाइल को लिखने के लिए खोलने के लिए किस मोड का उपयोग किया जाता है, जो फ़ाइल को ओवरराइट करता है?", pa: "ਇੱਕ ਫਾਈਲ ਨੂੰ ਲਿਖਣ ਲਈ ਖੋਲ੍ਹਣ ਲਈ ਕਿਹੜਾ ਮੋਡ ਵਰਤਿਆ ਜਾਂਦਾ ਹੈ, ਜੋ ਫਾਈਲ ਨੂੰ ਓਵਰਰਾਈਟ ਕਰਦਾ ਹੈ?" }, options: [{en: "'r'", hi: "'r'", pa: "'r'"}, {en: "'w'", hi: "'w'", pa: "'w'"}, {en: "'a'", hi: "'a'", pa: "'a'"}], correctAnswer: 1 },
        { question: { en: "Which function is used to close a file?", hi: "फ़ाइल को बंद करने के लिए किस फ़ंक्शन का उपयोग किया जाता है?", pa: "ਇੱਕ ਫਾਈਲ ਨੂੰ ਬੰਦ ਕਰਨ ਲਈ ਕਿਹੜਾ ਫੰਕਸ਼ਨ ਵਰਤਿਆ ਜਾਂਦਾ ਹੈ?" }, options: [{en: "close()", hi: "close()", pa: "close()"}, {en: "end()", hi: "end()", pa: "end()"}, {en: "finish()", hi: "finish()", pa: "finish()"}], correctAnswer: 0 },
        { question: { en: "To read the entire content of a file, you can use:", hi: "किसी फ़ाइल की संपूर्ण सामग्री को पढ़ने के लिए, आप उपयोग कर सकते हैं:", pa: "ਕਿਸੇ ਫਾਈਲ ਦੀ ਪੂਰੀ ਸਮੱਗਰੀ ਨੂੰ ਪੜ੍ਹਨ ਲਈ, ਤੁਸੀਂ ਵਰਤ ਸਕਦੇ ਹੋ:" }, options: [{en: "file.readline()", hi: "file.readline()", pa: "file.readline()"}, {en: "file.readlines()", hi: "file.readlines()", pa: "file.readlines()"}, {en: "file.read()", hi: "file.read()", pa: "file.read()"}], correctAnswer: 2 },
      ] },
  ],
  english: [
    { id: 'eng-11-1', grade: 11, title: { en: 'Reading: Unseen Passages', hi: 'पढ़ना: अनदेखे गद्यांश', pa: 'ਪੜ੍ਹਨਾ: ਅਣਦੇਖੇ ਪੈਰੇ' }, xp: 50, questions: [
      { question: { en: "What is the first step in answering questions about an unseen passage?", hi: "एक अनदेखे गद्यांश के बारे में सवालों के जवाब देने में पहला कदम क्या है?", pa: "ਇੱਕ ਅਣਦੇਖੇ ਪੈਰੇ ਬਾਰੇ ਸਵਾਲਾਂ ਦੇ ਜਵਾਬ ਦੇਣ ਵਿੱਚ ਪਹਿਲਾ ਕਦਮ ਕੀ ਹੈ?" }, options: [{en: "Read the questions first", hi: "पहले प्रश्न पढ़ें", pa: "ਪਹਿਲਾਂ ਸਵਾਲ ਪੜ੍ਹੋ"}, {en: "Read the passage carefully", hi: "गद्यांश को ध्यान से पढ़ें", pa: "ਪੈਰੇ ਨੂੰ ਧਿਆਨ ਨਾਲ ਪੜ੍ਹੋ"}, {en: "Start writing answers", hi: "उत्तर लिखना शुरू करें", pa: "ਜਵਾਬ ਲਿਖਣਾ ਸ਼ੁਰੂ ਕਰੋ"}], correctAnswer: 1 },
      { question: { en: "Finding the main idea of the passage helps in understanding its:", hi: "गद्यांश का मुख्य विचार खोजने से उसकी समझ में मदद मिलती है:", pa: "ਪੈਰੇ ਦਾ ਮੁੱਖ ਵਿਚਾਰ ਲੱਭਣ ਨਾਲ ਇਸਦੀ ਸਮਝ ਵਿੱਚ ਮਦਦ ਮਿਲਦੀ ਹੈ:" }, options: [{en: "Tone", hi: "स्वर", pa: "ਟੋਨ"}, {en: "Theme", hi: "विषय", pa: "ਥੀਮ"}, {en: "Length", hi: "लंबाई", pa: "ਲੰਬਾਈ"}], correctAnswer: 1 },
      { question: { en: "It is important to answer the questions in your:", hi: "सवालों के जवाब अपने में देना महत्वपूर्ण है:", pa: "ਸਵਾਲਾਂ ਦੇ ਜਵਾਬ ਆਪਣੇ ਵਿੱਚ ਦੇਣਾ ਮਹੱਤਵਪੂਰਨ ਹੈ:" }, options: [{en: "Own words", hi: "अपने शब्दों में", pa: "ਆਪਣੇ ਸ਼ਬਦਾਂ ਵਿੱਚ"}, {en: "Friend's words", hi: "दोस्त के शब्दों में", pa: "ਦੋਸਤ ਦੇ ਸ਼ਬਦਾਂ ਵਿੱਚ"}, {en: "Exact words from the passage", hi: "गद्यांश से सटीक शब्द", pa: "ਪੈਰੇ ਤੋਂ ਸਹੀ ਸ਼ਬਦ"}], correctAnswer: 0 },
    ] },
    { id: 'eng-11-2', grade: 11, title: { en: 'Grammar: Prepositions', hi: 'व्याकरण: पूर्वसर्ग', pa: 'ਵਿਆਕਰਨ: ਪ੍ਰੀਪੋਜ਼ੀਸ਼ਨਜ਼' }, xp: 60, questions: [
      { question: { en: "Complete the sentence: The book is ___ the table.", hi: "वाक्य पूरा करें: किताब ___ मेज पर है।", pa: "ਵਾਕ ਪੂਰਾ ਕਰੋ: ਕਿਤਾਬ ___ ਮੇਜ਼ 'ਤੇ ਹੈ।" }, options: [{en: "on", hi: "पर", pa: "'ਤੇ"}, {en: "in", hi: "में", pa: "ਵਿੱਚ"}, {en: "at", hi: "पर", pa: "'ਤੇ"}], correctAnswer: 0 },
      { question: { en: "Which preposition is used for time, like '___ 5 o'clock'?", hi: "समय के लिए कौन सा पूर्वसर्ग प्रयोग किया जाता है, जैसे '___ 5 बजे'?", pa: "ਸਮੇਂ ਲਈ ਕਿਹੜਾ ਪ੍ਰੀਪੋਜ਼ੀਸ਼ਨ ਵਰਤਿਆ ਜਾਂਦਾ ਹੈ, ਜਿਵੇਂ '___ 5 ਵਜੇ'?" }, options: [{en: "on", hi: "पर", pa: "'ਤੇ"}, {en: "in", hi: "में", pa: "ਵਿੱਚ"}, {en: "at", hi: "पर", pa: "'ਤੇ"}], correctAnswer: 2 },
      { question: { en: "He is afraid ___ dogs.", hi: "वह कुत्तों से डरता है।", pa: "ਉਹ ਕੁੱਤਿਆਂ ਤੋਂ ਡਰਦਾ ਹੈ।" }, options: [{en: "from", hi: "से", pa: "ਤੋਂ"}, {en: "of", hi: "से", pa: "ਤੋਂ"}, {en: "with", hi: "साथ", pa: "ਨਾਲ"}], correctAnswer: 1 },
    ] },
    { id: 'eng-12-1', grade: 12, title: { en: 'Writing: Note-Making', hi: 'लेखन: नोट-बनाना', pa: 'ਲਿਖਣਾ: ਨੋਟ-ਬਣਾਉਣਾ' }, xp: 60, questions: [
      { question: { en: "What is the main purpose of note-making?", hi: "नोट-बनाने का मुख्य उद्देश्य क्या है?", pa: "ਨੋਟ-ਬਣਾਉਣ ਦਾ ਮੁੱਖ ਉਦੇਸ਼ ਕੀ ਹੈ?" }, options: [{en: "To copy the text exactly", hi: "पाठ को हूबहू कॉपी करना", pa: "ਟੈਕਸਟ ਨੂੰ ਬਿਲਕੁਲ ਕਾਪੀ ਕਰਨਾ"}, {en: "To shorten the text and highlight key points", hi: "पाठ को छोटा करना और मुख्य बिंदुओं को उजागर करना", pa: "ਟੈਕਸਟ ਨੂੰ ਛੋਟਾ ਕਰਨਾ ਅਤੇ ਮੁੱਖ ਬਿੰਦੂਆਂ ਨੂੰ ਉਜਾਗਰ ਕਰਨਾ"}, {en: "To make the text longer", hi: "पाठ को लंबा करना", pa: "ਟੈਕਸਟ ਨੂੰ ਲੰਮਾ ਕਰਨਾ"}], correctAnswer: 1 },
      { question: { en: "Which of these should be used in note-making?", hi: "नोट-बनाने में इनमें से किसका उपयोग किया जाना चाहिए?", pa: "ਨੋਟ-ਬਣਾਉਣ ਵਿੱਚ ਇਹਨਾਂ ਵਿੱਚੋਂ ਕਿਸਦੀ ਵਰਤੋਂ ਕੀਤੀ ਜਾਣੀ ਚਾਹੀਦੀ ਹੈ?" }, options: [{en: "Full sentences", hi: "पूरे वाक्य", pa: "ਪੂਰੇ ਵਾਕ"}, {en: "Abbreviations and symbols", hi: "संक्षिप्ताक्षर और प्रतीक", pa: "ਸੰਖੇਪ ਅਤੇ ਚਿੰਨ੍ਹ"}, {en: "Long paragraphs", hi: "लंबे पैराग्राफ", pa: "ਲੰਬੇ ਪੈਰੇ"}], correctAnswer: 1 },
      { question: { en: "A suitable title is important for note-making because it:", hi: "नोट-बनाने के लिए एक उपयुक्त शीर्षक महत्वपूर्ण है क्योंकि यह:", pa: "ਨੋਟ-ਬਣਾਉਣ ਲਈ ਇੱਕ ਢੁਕਵਾਂ ਸਿਰਲੇਖ ਮਹੱਤਵਪੂਰਨ ਹੈ ਕਿਉਂਕਿ ਇਹ:" }, options: [{en: "Gives the main idea", hi: "मुख्य विचार देता है", pa: "ਮੁੱਖ ਵਿਚਾਰ ਦਿੰਦਾ ਹੈ"}, {en: "Makes it look nice", hi: "इसे अच्छा दिखाता है", pa: "ਇਸ ਨੂੰ ਵਧੀਆ ਦਿਖਾਉਂਦਾ ਹੈ"}, {en: "Adds length", hi: "लंबाई जोड़ता है", pa: "ਲੰਬਾਈ ਜੋੜਦਾ ਹੈ"}], correctAnswer: 0 },
    ] },
    { id: 'eng-12-2', grade: 12, title: { en: 'Flamingo: The Last Lesson', hi: 'फ्लेमिंगो: द लास्ट लेसन', pa: 'ਫਲੇਮਿੰਗੋ: ਆਖਰੀ ਸਬਕ' }, xp: 50, questions: [
      { question: { en: "Who is the author of 'The Last Lesson'?", hi: "'द लास्ट लेसन' के लेखक कौन हैं?", pa: "'ਆਖਰੀ ਸਬਕ' ਦਾ ਲੇਖਕ ਕੌਣ ਹੈ?" }, options: [{en: "Alphonse Daudet", hi: "अल्फोंस डौडेट", pa: "ਅਲਫੋਂਸ ਡੌਡੇਟ"}, {en: "William Shakespeare", hi: "विलियम शेक्सपियर", pa: "ਵਿਲੀਅਮ ਸ਼ੇਕਸਪੀਅਰ"}, {en: "John Keats", hi: "जॉन कीट्स", pa: "ਜੌਨ ਕੀਟਸ"}], correctAnswer: 0 },
      { question: { en: "The story is set during which war?", hi: "कहानी किस युद्ध के दौरान सेट है?", pa: "ਕਹਾਣੀ ਕਿਸ ਯੁੱਧ ਦੌਰਾਨ ਸੈੱਟ ਕੀਤੀ ਗਈ ਹੈ?" }, options: [{en: "World War I", hi: "प्रथम विश्व युद्ध", pa: "ਪਹਿਲੀ ਵਿਸ਼ਵ ਜੰਗ"}, {en: "Franco-Prussian War", hi: "फ्रेंको-प्रशियाई युद्ध", pa: "ਫ੍ਰੈਂਕੋ-ਪ੍ਰਸ਼ੀਅਨ ਯੁੱਧ"}, {en: "World War II", hi: "द्वितीय विश्व युद्ध", pa: "ਦੂਜੀ ਵਿਸ਼ਵ ਜੰਗ"}], correctAnswer: 1 },
      { question: { en: "What was Franz afraid of when he went to school that day?", hi: "उस दिन स्कूल जाते समय फ्रांज को किस बात का डर था?", pa: "ਉਸ ਦਿਨ ਸਕੂਲ ਜਾਂਦੇ ਸਮੇਂ ਫ੍ਰਾਂਜ਼ ਨੂੰ ਕਿਸ ਗੱਲ ਦਾ ਡਰ ਸੀ?" }, options: [{en: "A test on participles", hi: "कृदंत पर एक परीक्षण", pa: "ਪਾਰਟੀਸਿਪਲਜ਼ 'ਤੇ ਇੱਕ ਟੈਸਟ"}, {en: "Getting late", hi: "देर हो रही है", pa: "ਦੇਰ ਹੋ ਰਹੀ ਹੈ"}, {en: "The bulletin board", hi: "बुलेटिन बोर्ड", pa: "ਬੁਲੇਟਿਨ ਬੋਰਡ"}], correctAnswer: 0 },
    ] },
  ],
};

export const LEADERBOARD_DATA = [
    { name: 'Riya Sharma', xp: 4500 },
    { name: 'Karan Singh', xp: 4250 },
    { name: 'Priya Verma', xp: 3800 },
    { name: 'You', xp: 0 }, // This will be updated with the user's XP
    { name: 'Amit Kumar', xp: 3400 },
    { name: 'Simran Kaur', xp: 3100 },
];

// Generates a random date string in YYYY-MM-DD format within the last 30 days
const randomDate = () => {
  const end = new Date();
  const start = new Date();
  start.setDate(end.getDate() - 30);
  const randomTime = start.getTime() + Math.random() * (end.getTime() - start.getTime());
  return new Date(randomTime).toISOString().split('T')[0];
};

export const STUDENT_REPORTS: StudentReport[] = [
    { id: '1', name: 'Manpreet Singh', grade: 11, xp: 2500, streak: 12, lessonsCompleted: 8, totalLessonsInSubject: 10, subject: 'physics', averageScore: 85, lastActiveDate: randomDate() },
    { id: '2', name: 'Harleen Kaur', grade: 12, xp: 1800, streak: 5, lessonsCompleted: 5, totalLessonsInSubject: 8, subject: 'math', averageScore: 92, lastActiveDate: randomDate() },
    { id: '3', name: 'Sandeep Kumar', grade: 11, xp: 3200, streak: 20, lessonsCompleted: 10, totalLessonsInSubject: 10, subject: 'chemistry', averageScore: 95, lastActiveDate: randomDate() },
    { id: '4', name: 'Gurpreet Kaur', grade: 12, xp: 950, streak: 0, lessonsCompleted: 3, totalLessonsInSubject: 8, subject: 'biology', averageScore: 65, lastActiveDate: '2023-10-01' }, // old date to test inactive
    { id: '5', name: 'Amit Sharma', grade: 11, xp: 1200, streak: 3, lessonsCompleted: 4, totalLessonsInSubject: 9, subject: 'computer_science', averageScore: 78, lastActiveDate: randomDate() },
    { id: '6', name: 'Jasleen Kaur', grade: 12, xp: 450, streak: 1, lessonsCompleted: 2, totalLessonsInSubject: 7, subject: 'english', averageScore: 55, lastActiveDate: randomDate() }, // low score
    { id: '7', name: 'Rahul Verma', grade: 11, xp: 2800, streak: 15, lessonsCompleted: 9, totalLessonsInSubject: 10, subject: 'math', averageScore: 88, lastActiveDate: randomDate() },
    { id: '8', name: 'Simranjit Singh', grade: 12, xp: 2100, streak: 8, lessonsCompleted: 7, totalLessonsInSubject: 9, subject: 'physics', averageScore: 91, lastActiveDate: randomDate() },
];
